### PR TITLE
typescript: fix typings

### PR DESCRIPTION
**Pull request by larshp**
Hi,
Good to see some progress in the typescript area, thanks 💪 

I'm seeing the following issues in the definitions,
image

This PR fixex these issues

Note that https://github.com/types/mysql2 does not use https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mysql, but instead uses https://github.com/types/mysql

So I've changed it to use these typings intead

### CODE REVIEW

**Comment by sidorares** [comment]
do you know why https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mysql does not have published npm version? I have not followed types ecosystem development. Is this what gets imported at line 7 on your screenshot? How does it know that `import * as mysql from "mysql"` maps to `@types/mysql` dependency? Is it just convention, and `@types` is a special namespace?

**Comment by larshp** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mysql is published as https://www.npmjs.com/package/@types/mysql, but does not contain very much

https://github.com/types/mysql has more definitions, and is what is used in https://github.com/types/mysql2

its quite confusing 😄

**Comment by sidorares** [comment]
oh, I probably meant to ask "why https://github.com/types/mysql does not have published npm version?"
Happy to have it as github dep but wanted to understand some context

**Comment by larshp** [comment]
not sure 🤷‍♂️

**Comment by kanyuga** [comment]
@sidorares could you publish this fix? It solves an issue I was having with the code 

```
import { ConnectionOptions } from 'mysql2';

export type IConnectionConfig = Pick<
  ConnectionOptions,
  'host' | 'user' | 'password' | 'database' | 'port' | 'ssl' | 'dateStrings' | 'authPlugins'
>;
```

I was getting the following issue:

> error TS2344: Type '"host" | "user" | "password" | "database" | "port" | "ssl" | "dateStrings" | "authPlugins"' does not satisfy the constraint '"user" | "password" | "database" | "authPlugins" | "charsetNumber" | "compress" | "authSwitchHandler" | "connectAttributes" | "decimalNumbers" | "isServer" | "maxPreparedStatements" | ... 12 more ... | "timeout"'.
  Type '"host"' is not assignable to type '"user" | "password" | "database" | "authPlugins" | "charsetNumber" | "compress" | "authSwitchHandler" | "connectAttributes" | "decimalNumbers" | "isServer" | "maxPreparedStatements" | ... 12 more ... | "timeout"'.

**Comment by sidorares** [comment]
@kanyuga published as v2.2.3

**Pull request merged**
