### PR TITLE
Fix for #761

### PR DESCRIPTION
**Pull request by anliting**

### CODE REVIEW

**Comment by sidorares** [comment]
Thanks! Would you mind adding test for this?

**Comment by anliting** [comment]
Okay, I'll try.

**Comment by anliting** [comment]
Maybe we'll wait for this (https://github.com/mysqljs/mysql/issues/1978) if it's closing in a few days.

**Comment by anliting** [comment]
Tried; it seems that I have to investigate and setup too many things to code and run the test.

Maybe you can do it for me? The test should be "trying perform `pool.query` (`pool.format` has been good) with directly passed falsy values except for `undefined` and `null`". It should be like this:

```js
import assert from 'assert'
import mysql2 from 'mysql2'
let pool=mysql2.createPool({
    host:'localhost',
    user:'anliting',
    password:'',
})
for(let e of [false,0,'',NaN])
    pool.query('select ?',e,err=>assert(!err))
```

Besides, is this (https://github.com/sidorares/node-mysql2/blob/master/test/unit/test-Pool.js#L29) a bug? L33 and L39 also.

**Comment by sidorares** [comment]
no problems, I can add test to your pr

what do you think is wrong with L39?

```js
 const params = ['table name', 'thing'];
 assert.equal(
      pool.format('SELECT a FROM ?? WHERE b = ?', params),
      "SELECT a FROM `table name` WHERE b = 'thing'"
    );
```

**Comment by anliting** [comment]
We should test `promisePool` there, not `pool`, isn't it?

**Comment by sidorares** [comment]
I don't think so, this is unit test for non-promise version of pool

**Comment by sidorares** [comment]
this is promise pool test: https://github.com/sidorares/node-mysql2/blob/5c5aa3aed7e772e599dbefdafb04405672901808/test/integration/promise-wrappers/test-promise-wrappers.js#L250-L268

**Comment by anliting** [comment]
But L27-L43 is almost the same as L8-L24, and promisePool created on L26 is not being referenced anywhere.

**Comment by sidorares** [comment]
oh, you are right. It's probably a bug

**Comment by kibertoad** [comment]
@sidorares What is left for this PR to be finished? Do you need any help?

**Comment by sidorares** [comment]
@kibertoad I think it can be merged. Can you have a look and review it as well @kibertoad ? Any concerns from you?

**Comment by kibertoad** [comment]
@sidorares 
1) I'm not too comfortable with having no tests for the change;
2) Formatting seems to be off, no spaces;
3) Does specific "=== undefined" (as opposed "not truthy") make sense here?

**Comment by anliting** [comment]
@kibertoad 
For the "3. Does ...": I think it make sense here. `e0===undefined?e1:e0` have different semantic comparing to `e0||e1`.

**Pull request closed without merging**
