### PR TITLE
fix: remove accidental log in caching_sha2_password.js

### PR DESCRIPTION
**Pull request by sthuck**

### CODE REVIEW

**Comment by daniellockyer** [comment]
@sidorares would you be able to look at merging this? Our internal tools started spewing public key logs 😅

**Comment by sidorares** [comment]
sure @daniellockyer

**Comment by sidorares** [comment]
at least thats a public key 😅

**Comment by sidorares** [comment]
@daniellockyer @sthuck done - https://github.com/sidorares/node-mysql2/releases/tag/v3.1.1

**Comment by daniellockyer** [comment]
Thanks as always!

**Pull request merged**
