### PR TITLE
Milliseconds for setting date values

### PR DESCRIPTION
**Pull request by vasyas**

### CODE REVIEW

**Comment by sidorares** [comment]
Thanks! Would you be able to also add test for this?

**Comment by vasyas** [comment]
Ok, will do.

**Comment by vasyas** [comment]
Add tests in test-datetime.js. Also, updated how fractional seconds are read for tests to be working.
For this I also changed behavior in test-#617.js, now dateStrings is reflecting precision set on column type. Please review.

**Comment by sidorares** [comment]
Looks good!

Note that in binary protocol ( aka 'prepared statements' ) we currently send everything as a string while for some types it might have more sense to use better types ( for example js dates serialise back using DATETIME )

**Pull request merged**
