### PR TITLE
Fix node encodings lookup in string parser

### LINKED ISSUE #582: string parser looks up in NODE_ENCODING incorrectly
Is this a bug?

https://github.com/sidorares/node-mysql2/blob/master/lib/parsers/string.js#L15
https://github.com/sidorares/node-mysql2/blob/master/lib/parsers/string.js#L28

`NODE_ENCODING` here is an array, `encoding` function arguments receives string values like `binary`, `cesu8`, `utf8`, etc (at least, in `decode` function). They will never be found using `encoding` variable as array key. Looks like we should scan array using `.indexOf` for this to work properly.

Does triggering `Iconv` decoder for every charset could give significant performance penalty on parsing rows?

### PR DESCRIPTION
**Pull request by dolphin278**
This fixes #582

### CODE REVIEW

**Comment by dolphin278** [comment]
`latin1` is not supported in Node v4.x (this behavior was hidden due to bug we trying to fix here):

* https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html#buffer_buffers_and_character_encodings
* https://nodejs.org/dist/latest-v7.x/docs/api/buffer.html#buffer_buffers_and_character_encodings

What should we do? Treat is as non node-supported one for compat, or check for Node version. @sidorares @sushantdhiman ?

**Comment by dolphin278** [comment]
Figured it out - we could use `Buffer.isEncoding` at startup time.

**Comment by dolphin278** [comment]
All done, test passed.

**Comment by sidorares** [comment]
Thanks @dolphin278 !

**Comment by dolphin278** [comment]
👍

**Comment by dolphin278** [comment]
@sidorares when are you planning next npm release?

**Comment by sidorares** [comment]
@dolphin278 done, v1.3.3 ( changelog: d5defad183fdc9d17a0457e16b9e567bf6be1ca3  )

**Comment by dolphin278** [comment]
@sidorares Thank you!

**Pull request merged**
