### PR TITLE
fix: revert breaking change in results creation

### PR DESCRIPTION
**Pull request by wellwelwel**
The previous solution (#2574) aimed to create a clean object, but it caused a major change.

Instead, I just grouped the object's native properties:

```js
const privateObjectProps = new Set([
  '__defineGetter__',
  '__defineSetter__',
  '__lookupGetter__',
  '__lookupSetter__',
  '__proto__',
]);
```

Then, it will perform a simple validation to ensure that the `fields[i].name` is safe:

```js
if (helpers.privateObjectProps.has(fields[i].name)) {
  throw new Error(
    `The field name (${fieldName}) can't be the same as an object's private property.`,
  );
}
```

By this way, it's possible to:

- use the native methods available from an object
- deep compare results with an expected variable
- test the vulnerability without use a query for that
- If an user, for some reason, wants to create or customize a `prototype` after the query has been finished, they can

> Basically, as it should be 🙋🏻‍♂️

### CODE REVIEW

**Comment by wellwelwel** [comment]
@ert78gb, I included a simple test to ensure your repro:

```js
const expected = [
      {
        test: 2,
      },
    ];

const [results] = await connection.query('SELECT 1+1 AS `test`');

assert.deepStrictEqual(results, expected, 'Ensure clean object "results"');
```

**Comment by sidorares** [comment]
Let's run some benchmarks before merging

**Comment by wellwelwel** [comment]
Particularly, I don't like this solution, even if the benchmark is good (I think it's too much).

Even using freeze, this would still be a major change, as we would be blocking the user if they later wanted to use a prototype of their own.

---

> I believe this could be much simpler 💡

Instead of creating a complex object, we can just check if the `field` is not on a blacklist, without even needing to `freeze`. For example:

```js
const nativeProps = ['__proto__', 'hasOwnProperty', 'toString', 'valueOf'];

if (nativeProps.includes(field)) {
  // error
}
```

Now, we keep it safe, we don't cause any breaks, and we keep the solution simple and the user can use, change and create any prototype they need.

> For now, I'm just thinking about it, but I believe it could be a definitive solution.

**Comment by wellwelwel** [comment]
@sidorares, I rewrote the logic and description of the _PR_.

Could you check again? 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
Testing all the standard object properties, considering **Node.js** long term versions:

```js
const emptyObject = {};
const proto = Object.getPrototypeOf(emptyObject);
const nativeObjectProps = Object.getOwnPropertyNames(proto);

const blockedFields = nativeObjectProps.map((prop) => [{ name: prop }]);

blockedFields.forEach((fields) => {
  try {
    getBinaryParser(fields, {}, {});
    assert.fail('An error were expected');
  } catch (error) {
    assert.strictEqual(
      error.message,
      `The field name (${srcEscape(fields[0].name)}) cannot be the same as the property of a native object.`,
      `Ensure safe ${fields[0].name}`,
    );
  }
});
```

- Supposing that someday **Node.js** includes some new method/property, this test will fail 🔐
- Same idea to `TextRowParser`.

**Comment by wellwelwel** [comment]
> Using `Set` and `has`, instead of `Array` and `includes` due to:

Basic benchmark:

```js
const benchmarkArrayIncludes = (field) => {
  const nativeObjectProps = [
    '__defineGetter__',
    '__defineSetter__',
    '__lookupGetter__',
    '__lookupSetter__',
    '__proto__',
    'constructor',
    'hasOwnProperty',
    'isPrototypeOf',
    'propertyIsEnumerable',
    'toLocaleString',
    'toString',
    'valueOf',
  ];

  console.time('Array.includes');
  for (let i = 0; i < 1000000; i++) nativeObjectProps.includes(field);
  console.timeEnd('Array.includes');
};

const benchmarkSetHas = (field) => {
  const nativeObjectProps = new Set([
    '__defineGetter__',
    '__defineSetter__',
    '__lookupGetter__',
    '__lookupSetter__',
    '__proto__',
    'constructor',
    'hasOwnProperty',
    'isPrototypeOf',
    'propertyIsEnumerable',
    'toLocaleString',
    'toString',
    'valueOf',
  ]);

  console.time('Set.has');
  for (let i = 0; i < 1000000; i++) nativeObjectProps.has(field);
  console.timeEnd('Set.has');
};

for (let i = 0; i < 5; i++) benchmarkArrayIncludes('field');
for (let i = 0; i < 5; i++) benchmarkSetHas('field');
```

---

Results:

```
Array.includes: 1.891ms
Array.includes: 0.586ms
Array.includes: 0.593ms
Array.includes: 0.59ms
Array.includes: 0.646ms
Set.has: 1.228ms
Set.has: 0.563ms
Set.has: 0.563ms
Set.has: 0.561ms
Set.has: 0.559ms
```

---

Compatibility:

`Set`: [Node.js 0.12.18](https://node.green/#ES2015-built-ins-Set).

**Comment by wellwelwel** [comment]
Bringing a comment here: https://github.com/sidorares/node-mysql2/commit/74abf9ef94d76114d9a09415e28b496522a94805#r140992502 🤝

**Comment by wellwelwel** [comment]
> As suggested by @sidorares:

Instead of checking the field name manually, we have some alternatives:

- Refactor the `results` object to a mapped object
- Keep it as `Object.create(null)` by adding a config option to use a standard object for results (not sure about bump a major version for this)

> Although the issue #2585 doesn't have that many interactions, I think it's important to consider the users who don't participate directly 🙋🏻‍♂️

**Review by sidorares — APPROVED** [review]

**Comment by wellwelwel** [comment]
@sidorares, can we merge this? 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
Merging this.

For a major bump version, I recommend reverting this PR and include a safer approach in **docs** such as:

```js
const obj = Object.create(null);

obj.test = true;

Object.hasOwn(obj, 'test'); // ✅
```

**Pull request merged**
