### PR TITLE
docs: introduce documentation website

### PR DESCRIPTION
**Pull request by wellwelwel**
## Introducing a documentation website 🦖✨

> For now, I'm testing it in a temporary repository to see everything working on **GitHub Pages**. 
> Feel free to check how it's going in [https://wellwelwel.github.io/node-mysql2-website-test](https://wellwelwel.github.io/node-mysql2-website-test).

---

### How it works (for now)?

- After merged, it will create a new branch (`gh-pages`) and compile the website in this branch.
- By setting the Pages settings to `gh-pages` branch, it will create a **GitHub** URL (https://sidorares.github.io/node-mysql2) with this branch content
- Both the website's `package.json` and `package-lock.json` are separate from main code.

---

- Before merge it:
  - **Settings > Actions > General > Workflow permissions**:
    - Check if it's flagged as `Read and write permissions`.

- After merge it:
  - **Settings > Pages > Source**:
    - Select `Deploy from a branch`
  - **Settings > Pages > Branch**: 
    - Select `gh-pages`
  
---

Unofficial temporary _**favicon**_ (this isn't a logo):

> Example:
> Screenshot 2023-11-21 at 01 35 42

---

### TODO

- [x] Include all `.md` files
- [x] Include a free search tool (similar to **Algolia**)
- [x] Migrate translations
- [x] Check for lint rules and build tests
- [x] Include examples
- [x] Components
  - [x] `History`
  - [x] `Stability`
  - [x] `FAQ`
- [x] Pages
  - [x] **Stability Badges**
  - [x] **FAQ**
    - [x] At least one question
- [x] Review and test links
- [x] Create the **website** **Contributing**

---

### Tech stack includes:

- [Docusaurus](https://docusaurus.io/)
  - [React](https://react.dev/) (`.tsx` files)
  - [MDX](https://mdxjs.com/) (`.mdx` files)
  - [Saas](https://sass-lang.com/) (`.scss` files)
- [TypeScript](https://www.typescriptlang.org/) (`.ts` files)

---

Naturally, ask any questions you like 🧙🏻

---

<details>
<summary>
<h3>To discuss (<i>resolved</i>)</h3>
</summary>

- [x] I opted for a 100% free format, so it uses **GitHub Pages** to serve the website and provides a free domain.~
- [x] I've chosen to show examples based on `promise-based` first.
- [x] As said in https://github.com/sidorares/node-mysql2/issues/2263#issuecomment-1791476781, I'm using the current documentation and examples to start it. Naturally, increasing more complete documentation in the long term.
- [x] Only after (_if_) this **PR** is approved, remove the "old" documentation and direct it to the website (in a new **PR**).
</details>

### CODE REVIEW

**Comment by wellwelwel** [comment]
Testing the documentation search 🕵🏻

Screenshot 2023-11-14 at 05 09 02

**Comment by sidorares** [comment]
I'd like to balance "light and simple to navigate" vs "complete" so feel free to push on these suggestions. What do you think about adding:

- "stability" badge, similar to what [node docs use](https://nodejs.org/dist/latest-v21.x/docs/api/documentation.html#stability-index) 
- history ( at least "version when api was introduced" )
- link to mysql wire docs, for example AuthSwitch would link to https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html#sect_protocol_connection_phase_auth_method_mismatch_method_change

happy to discuss that later and if we agree to add have as a later change

**Comment by sidorares** [comment]
we could potentially use https://mysql2.js.org domain . To get it we would need to open https://github.com/js-org/js.org/pulls PR and get it approved and merged

**Comment by sidorares** [comment]
> version when api was introduced

see "history" blocks in nodejs docs, for example here https://nodejs.org/api/async_hooks.html#class-asynchook

Basically an earliest version before which documented api cannot be used

image

**Comment by wellwelwel** [comment]
Ah, to create something similar (manually), we can use a `table` and the `details` tag in markdown:

```md
## `async_hooks.executionAsyncId()`

<details open>
  <summary>History</summary>

  | Version | Changes                   |
  |---------|---------------------------|
  | v8.2.0. | Renamed from `currentId`. |
  | v8.1.0  | Added in: v8.1.0          |
</details>
```

*That prints:*

## `async_hooks.executionAsyncId()`

<details open>
  <summary>History</summary>

  | Version | Changes                   |
  |---------|---------------------------|
  | v8.2.0. | Renamed from `currentId`. |
  | v8.1.0  | Added in: v8.1.0          |
</details>

---

Differently from `.md`, we can also change its style 👩🏻‍🎤

> To generate this automatically, I don't know a tool that does it, but I think it's would be like a change log tool.

**Comment by wellwelwel** [comment]
Also, it's possible to create a component and use this like:

**MDX file:**
```mdx
## `async_hooks.executionAsyncId()`

<History data={[
  { version: '8.2.0', changes: 'Renamed from currentId.' },
  { version: '8.1.0', changes: 'Added in: v8.1.0 ' },
]}>

- Returns: [<number>](#) The asyncId of the current execution context. Useful to track when something calls.
```

**Comment by wellwelwel** [comment]
Hey @sidorares, a simple question about options: **A or B**?

- **A (original):**
  - Screenshot 2023-11-20 at 06 05 40

- **B:**
  - Screenshot 2023-11-20 at 06 04 09

---

> For now, I will keep it as it is (**A**) 👩🏻‍🎤

**Comment by wellwelwel** [comment]
@sidorares, in [docs: migrate examples](https://github.com/sidorares/node-mysql2/pull/2279/commits/72dc78665e69203fdb10109e2b173a8d5320bed4), it alerts many false positives in the examples.

I'll try to move the examples from `.js` files to `.mdx` files too.

Advantages:
- Possibility to search within examples
- It will probably solve the CodeQL false positives in examples

**Comment by wellwelwel** [comment]
Hey @sidorares, almost there 🌞
 
---

### Stability Badge (by default)
Screenshot 2023-11-26 at 00 00 05

---

### Stability Badge (with an optional description)
Screenshot 2023-11-25 at 23 59 25

---

### History

https://github.com/sidorares/node-mysql2/assets/46850407/c3b94418-f6e0-4751-9b6f-9c90221377a1

**Comment by wellwelwel** [comment]
Also, it's now possible to dynamically search both the documentation and examples 🌞✨

**Comment by wellwelwel** [comment]
> Now it's on! ☘️

---

### History
> Light and Dark themes

#### Example usage (MDX):

```tsx
<History
  records={[
    {
      version: '3.5.2',
      changes: [
        'Some change description',
      ],
    },
  ]}
/>
```

https://github.com/sidorares/node-mysql2/assets/46850407/2f0b170f-49ce-4d1a-9212-0ba59616e9d7

---

### Stability Badge _(default)_
> Light and Dark themes

#### Example usage (MDX):

```tsx
<Stability level={2} />
```

https://github.com/sidorares/node-mysql2/assets/46850407/7bdbacb3-7356-49fb-84a7-4f41b4665ba1

---

### Stability Badge _(with a optional description)_
> Light and Dark themes

#### Example usage (MDX):

```tsx
<Stability level={0} message='An optional message here.' />
```

https://github.com/sidorares/node-mysql2/assets/46850407/248194fc-e9c1-48c4-b5b4-10c13d15bc29

**Comment by wellwelwel** [comment]
@sidorares, finally, it's ready 🎉✨

---

### Notes
- This *PR* keeps everything intact with absolutely *0* deletions
- No documentation was modified or added, except for:
  - In **README.md**, added both `promise` and `callback` examples.
  - I've used the **Stability Badges** and `History` in the **TypeScript** documentation.
- Documentation and examples can now be searched dynamically
- The search works for all languages and searches all pages for each language
  - 🇺🇸
  - 🇨🇳
  - 🇧🇷
- I introduced some of the ideas we discussed:
  - `History`
  - `Stability`
  - **Stability Badges** page (_derived and shaped from the equivalent section in the Node.js documentation_)
  - **FAQ** page
    - I created the "**How to handle errors?**" FAQ as a starting point for subsequent FAQ contents

---

### What's Next?

- About https://mysql2.js.org domain, it needs the link working before to open a *PR*.
- Next up, the new challenge is to create all the long-term documentation.
- **And the most important question:** How do you feel about this initial state? 🥹

---

### Overview

- **Stability Badges**
  - https://wellwelwel.github.io/node-mysql2-website-test/docs/stability-badges
- `History`
  - https://wellwelwel.github.io/node-mysql2-website-test/docs/documentation/typescript-examples#resultsetheader
- FAQ ("**How to handle errors?**")
  - https://wellwelwel.github.io/node-mysql2-website-test/docs/faq/how-to-handle-errors

**Comment by wellwelwel** [comment]
Just some refinements and a **Donate** following link to https://github.com/sponsors/sidorares 🌞

**Comment by sidorares** [comment]
sorry very busy last few days but I promise I'll give some attention very soon!

**Comment by wellwelwel** [comment]
> sorry very busy last few days but I promise I'll give some attention very soon!

Hey, it's okay, thank you and no worries! 🤝✨

**Comment by wellwelwel** [comment]
Yeah 🎉

The second step would be to remove the "old" docs and examples from `/docs` and `/examples`, and then adapt `README.md` to suggest the website, naturally concentrating the documentation and examples in just one place.

> Still not changing any current documentation

I'd like to get this done before I go on my vacation 🌞

**Comment by wellwelwel** [comment]
@sidorares , a small suggestion would be to flag the "**Use your GitHub Pages website**" on repository details:

Screenshot 2023-12-20 at 18 55 01

---

Then:

Screenshot 2023-12-20 at 18 58 31

**Comment by sidorares** [comment]
done, thanks for the suggestion!

**Pull request merged**
