### PR TITLE
fix issue #1040

### LINKED ISSUE #1040: datetime fields returned as date when time is 00:00:00
Setting a DATETIME field with the value 2019-10-01 00:00:00
Then retrieve the data using the execute command:
`const [result] = connection.execute('SELECT * FROM my_table', [])`

result will equal to '2019-10-01' instead of '2019-10-01 00:00:00' although it's a DATETIME field and not merely a DATE

note that when using query the behavior is as expected

### PR DESCRIPTION
**Pull request by sidorares**
Fixes #1040.

### CODE REVIEW

**Comment by testn** [comment]
@sidorares  Let's merge this?

**Comment by sidorares** [comment]
I'll try to rebase tonight so all the latest Ci scripts can run

**Comment by w666** [comment]
Hi @sidorares,

My team just hit this issue, and this is a critical bug for us. Would it be possible to merge and release it? Thanks.

**Comment by sidorares** [comment]
@w666 could you tru to recreate a PR with a fix, either using identical changes ( sans conflicts ) or more modernised ( maybe use poku-style unit tests, see other recently added tests )? Unfortunately this PR slipped out of my attention and is 4.5 years old now

**Comment by wellwelwel** [comment]
Closing due to #3204.

**Pull request closed without merging**
