### PR TITLE
Promise Wrapper extension

### PR DESCRIPTION
**Pull request by Hookyns**
Third parameter (callback) added to PromiseConnection.prototype.query and PromiseConnection.prototype.execute which makes original query and execute return values available.

### CODE REVIEW

**Comment by sidorares** [comment]
feels a bit strange to me - why promise wrapper in the first place if callback required? Can you describe your use case?

**Comment by Hookyns** [comment]
I'm awaiting promise as usual but I want to log executed query which is stored in original return object in sql property. This is quite clear way (for me) how to access that returned object like.. "hey btw,.. what was original return value?"

Or is there another way how to access executed SQL when using promise?

**Comment by Hookyns** [comment]
I've pushed new commit which change the first one solution with callback to the last one I've mentioned in comment above as EDIT4. Feel free to reject this PR if you don't like it. I can rewrite it just in my project, but it would be nice to have access to executed SQL.

**Comment by sidorares** [comment]
I prefer this to be done by other means - calling `format(sql, parameters)` upfront or maybe introducing some generic hooks mechanism for logging and extension

**Pull request closed without merging**
