### PR TITLE
fix: The removeIdleTimeoutConnectionsTimer did not clean up when the …

### PR DESCRIPTION
**Pull request by foxling**
…pool was closed.

 #1917

### CODE REVIEW

**Comment by wellwelwel** [comment]
Thanks, @foxling 🙋🏻‍♂️

Do you think there is a way to test it in an unit test? Maybe we can use the steps from https://github.com/sidorares/node-mysql2/issues/1917#issue-1641776181.

**Comment by sidorares** [comment]
happy to merge without a unit test ( but if we can add - great ). We need to detect leaking timer handles though, the test https://github.com/sidorares/node-mysql2/issues/1917#issue-1641776181 would pass OK but the process then won't exit for some time. As an option - spawn test in its own child process and expect it to finish within reasonable time

**Comment by foxling** [comment]
[setTimeout(() => process.exit(0), 1000)](https://github.com/sidorares/node-mysql2/pull/2384/files#diff-3ee61ffd0d1ccbda2b1eaa017a4e2cd3e60b34141199a2ec75655e90315fd8f7L41)
In this unit test, which probably encountered this problem at that time, removing this code would fit the test scenario, so is that it?

**Comment by wellwelwel** [comment]
> [setTimeout(() => process.exit(0), 1000)](https://github.com/sidorares/node-mysql2/pull/2384/files#diff-3ee61ffd0d1ccbda2b1eaa017a4e2cd3e60b34141199a2ec75655e90315fd8f7L41) In this unit test, which probably encountered this problem at that time, removing this code would fit the test scenario, so is that it?

@foxling, that makes sense to me.

@sidorares, can we merge it?

**Pull request merged**
