### PR TITLE
Add .value() method to the typeCast field wrapper

### PR DESCRIPTION
**Pull request by Parsonswy**
I was a bit crude here and most or less copy pasted the `readCodeFor` methods that compile the parser and am open to other approaches.

Another option I considered was modifying the compiled parser so that it could be invoked recursively, but I felt that was going to be a bit hacky since `wrap()` would need to be able to invoke the parser, but the parser is defined using `wrap`. It would avoid duplicating the switch statement though.

I also included a simple benchmark that compares querying with default the default cast behavior, custom type cast with the current wrapper methods, and type cast using the added `.value()` method.

These are the results on my machine against a local docker container with mysql 8.3.0.
```
query raw: AVG 0.0762ms
query typecast.string(): AVG 0.0705ms
query typecast.value(): AVG 0.0677ms
```

### CODE REVIEW

**Comment by wellwelwel** [comment]
Thanks, @Parsonswy 🚀

There are some **Sequelize** traces on `typeCast` + `execute` that I believe the issues come from **MySQL2**:

- https://github.com/wellwelwel/sequelize/issues/1

> I think these changes can clarify this issue. As soon as possible I intend to check it out in detail 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
A question: this _PR_ would work as a `feat`, right?

Regardless of benchmark, do you think it's possible to make these modifications without "keeping" the breaking changes you mentioned in https://github.com/sidorares/node-mysql2/issues/1446#issuecomment-2067516735?

**Comment by sidorares** [comment]
I'm a bit confused. What's the difference between added `readCodeFor` and existing `readValueFor` ?
Also looks like what we currently pass as a second parameter ( "next()" function ) to a typeCast call is what we actually need from `value()`? Which means that we only need to update documentation

instead of 

```js
  typeCast: function (field, next) {
    if (field.type === 'LONGLONG') {
      return field.string() === '1';
    }
    return next();
  },
```

we can have an example

```js
  typeCast: function (field, getValue) {
    const value = getValue();
    if (field.type === 'LONGLONG') {
      return value === '1';
    }
    return value;
  },
```

And later we can deprecate `typeCast` and introduce `mapValue` which would get value as a parameter:

```js
  mapValue: function (field, value) {
    if (field.type === 'LONGLONG') {
      return value === '1';
    }
    return value;
  },
```

**Comment by Parsonswy** [comment]
>Regardless of benchmark, do you think it's possible to make these modifications without "keeping" the breaking changes you mentioned in https://github.com/sidorares/node-mysql2/issues/1446#issuecomment-2067516735

I don't think I understand the question. By "breaking change" I meant invoking `typeCast` on binary results at all was a break as there are results which when handled by text protocol with a given implementation of `typeCast`will work, but the same implementation would then break if the results are binary parsed. I don't think this PR would have introduced a revert of a breaking change.

Going forward, I don't think it is safe to use the `read*` methods on the field wrapper though because of that text/bin discrepancy. I think the safe/protocol agnostic way to cast is what @sidorares pointed out.

> Also looks like what we currently pass as a second parameter ( "next()" function ) to a typeCast call is what we actually need from value()? Which means that we only need to update documentation.

Hmm. Yes. I think this is totally possible with the current API and I just zeroed in on `.value()`. Updating the docs to to codify that it is ok to invoke `next();` as a way to get a "default" deserialization of the MySQL value and then perform any casting off of that makes sense to me.

I think I can close this PR, but will wait for further comment. Maybe the benchmarks are useful?

**Comment by sidorares** [comment]
let's close `.value()` for now and potentially focus on re-packaging it via documentation changes

`typeCast` benchmarks would be definitely valuable

**Comment by max-zu** [comment]
Any progress on this ? We need to update mysql2 package due to [this](https://github.com/sidorares/node-mysql2/pull/2608) security update. But we can't due to this bug https://github.com/sequelize/sequelize/issues/17141

**Comment by wellwelwel** [comment]
@max-zu

> Any progress on this ? We need to update mysql2 package due to [this](https://github.com/sidorares/node-mysql2/pull/2608) security update. But we can't due to this bug [sequelize/sequelize#17141](https://github.com/sequelize/sequelize/issues/17141)

Although the main issue was opened in **Sequelize**, the issue is seems closer to this https://github.com/sidorares/node-mysql2/issues/1446#issuecomment-2067516735 than to **Sequelize**.

Unfortunately I haven't been able to reproduce this error _(from **Sequelize**)_ using **MySQL2** only. Any help on this would be appreciated.

**Pull request closed without merging**
