### PR TITLE
Implement sha256_password authentication plugin

### LINKED ISSUE #1152: Error: Server requests authentication using unknown plugin sha256_password
Started receiving this error from Ubuntu 20.04's mysql 8.0.19. My users are using `caching_sha2_password` and the server default is also set to that, however it's still requesting `sha256_password`. This may be a bug in Ubuntu's mysql build, but I went ahead an made an implementation of the auth plugin for node-mysql2 and will post a PR.

```
Error: Server requests authentication using unknown plugin sha256_password. See TODO: add plugins doco here on how to configure or author authentication plugins.
    at Object.authSwitchRequest (node_modules/mysql2/lib/commands/auth_switch.js:46:11)
    at ClientHandshake.handshakeResult (node_modules/mysql2/lib/commands/client_handshake.js:150:22)
    at ClientHandshake.execute (node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (node_modules/mysql2/lib/connection.js:417:32)
```

### PR DESCRIPTION
**Pull request by kellycampbell**
Fixes #1152

### CODE REVIEW

**Comment by sidorares** [comment]
I'd like to test it locally first, can you give instructions on how to set up a server with  sha256_password user?

**Comment by kellycampbell** [comment]
```
create user 'sha256_test'@'%' identified with sha256_password by 'password';
```

https://dev.mysql.com/doc/refman/8.0/en/sha256-pluggable-authentication.html

**Comment by sidorares** [comment]
given that the plugin is deprecated another option might be to ship this plugin as external module. This would require some extra setup for users that need it but won't increase size/complexity of the module for those who don't need sha256_password auth

**Comment by kellycampbell** [comment]
I couldn't find the root cause in mysql but did see other similar reports. Even though it is deprecated, it's still in use and likely causing problems for users who need to connect to databases using it. Default Ubuntu 20.04 released a few weeks ago is where I'm experiencing it out of the box.

I found one team at my company using a workaround of making all the team's devs create their mysql users with `IDENTIFIED WITH mysql_native_password` added.

The `mysql` npm module has a similar problem but doesn't report it well. I can't tell from the error message or stack if it's failing on cached_sha2 or sha256. I don't think they implement either yet.
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

The implementation is tiny and almost identical to the caching_sha2 one (because I copied most of the code and trimmed out the stuff that didn't apply). It would be nice if the library just worked out of the box for what seems to be a common issue.

**Comment by sixmen** [comment]
I'm using sha256_password with MySQL 5.7. So I'm glad to include this plugin to the module.

(Currently, I'm using extracted plugin function and custom authPlugins settings)

**Comment by sidorares** [comment]
I'm happy to include it @kellycampbell @sixmen , sorry didn't have much time lately to work through backlog of PRs

**Pull request merged**
