### PR TITLE
feat: Add jsonStrings configuration

### PR DESCRIPTION
**Pull request by rubenmorim**
Added configuration to support jsonStrings.
Check https://github.com/sidorares/node-mysql2/issues/1072 for more details about this feat

### CODE REVIEW

**Review by wlarch — APPROVED** [review]
Seems perfectly legit to me. 💪

**Comment by wellwelwel** [comment]
Hey, @rubenmorim. Thanks 🚀

---

I believe the changes also fit the binary parser:
https://github.com/sidorares/node-mysql2/blob/e536b4151a06ef7e4637393714c4058162fc23a1/lib/parsers/binary_parser.js#L62

---

For _typings_, we can include the option `jsonStrings` to [node-mysql2/typings/mysql/lib/Connection.d.ts](https://github.com/sidorares/node-mysql2/blob/e536b4151a06ef7e4637393714c4058162fc23a1/typings/mysql/lib/Connection.d.ts#L82-L329) and [node-mysql2/typings/mysql/lib/protocol/sequences/Query.d.ts](https://github.com/sidorares/node-mysql2/blob/e536b4151a06ef7e4637393714c4058162fc23a1/typings/mysql/lib/protocol/sequences/Query.d.ts#L6-L86):

```ts
{
  jsonStrings?: boolean;
}
```

---

We could have a basic test for `execute` and `query`. What do you think? 🙋🏻‍♂️
For example, something like:

```sql
SELECT CAST('{"test": true}' AS JSON) AS json_result;
```

**Comment by sidorares** [comment]
lgtm, in addition to @wellwelwel comments - maybe also add a bit of documentation somewhere in https://github.com/sidorares/node-mysql2/tree/master/website/docs/documentation

**Comment by wellwelwel** [comment]
Linking to another issue, the added documentation also closes:

- #2181

**Comment by wellwelwel** [comment]
Thanks again, @rubenmorim. I'll include the tests in a separate _PR_.

As `true`

```js
  test(async () => {
    const [result] = await connection.query(
      `SELECT CAST('{"test": true}' AS JSON) AS json_result`,
    );

    assert.deepStrictEqual(
      result[0].json_result,
      '{"test": true}',
      'Ensure JSON return as string (query)',
    );
  })

  test(async () => {
    const [result] = await connection.execute(
      `SELECT CAST('{"test": true}' AS JSON) AS json_result`,
    );

    assert.deepStrictEqual(
      result[0].json_result,
      '{"test": true}',
      'Ensure JSON return as string (execute)',
    );
  })
```

As `false` (default)

```js
  test(async () => {
    const [result] = await connection.query(
      `SELECT CAST('{"test": true}' AS JSON) AS json_result`,
    );

    assert.deepStrictEqual(
      result[0].json_result,
      { test: true },
      'Ensure JSON return parsed (query)',
    );
  })

  test(async () => {
    const [result] = await connection.execute(
      `SELECT CAST('{"test": true}' AS JSON) AS json_result`,
    );

    assert.deepStrictEqual(
      result[0].json_result,
      { test: true },
      'Ensure JSON return parsed (execute)',
    );
  })
```

**Comment by rubenmorim** [comment]
> Thanks again, @rubenmorim. I'll include the tests in a separate _PR_ (#2720).

Great ! thank you guys @sidorares @wellwelwel

**Pull request merged**
