### PR TITLE
Added access to the "sqlMessage" of an error

### PR DESCRIPTION
**Pull request by williamdes**
I was using [github:mysqljs/mysql](https://github.com/mysqljs/mysql) and I changed to node-mysql2.

We dont have access to sqlMessage with node-mysql2 so I added it :)

**My tests**
With node-mysql2 :
```javascript
var mysql = require('mysql2');
var connection = mysql.createConnection({user: 'xx', password: 'xxx', database: 'xx', host: 'xxx'});

connection.query("SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'MY_ERR';", function (err, rows) {
  console.log(JSON.stringify(err));
/*
Before : {"code":"ER_SIGNAL_EXCEPTION","errno":1644,"sqlState":"#45000"}
After : {"code":"ER_SIGNAL_EXCEPTION","errno":1644,"sqlState":"#45000","sqlMessage":"MY_ERR"}
*/
});
```
With mysql from [github:mysqljs/mysql](https://github.com/mysqljs/mysql)
```javascript
var mysql = require('mysql');
var connection = mysql.createConnection({user: 'xx', password: 'xxx', database: 'xx', host: 'xxx'});

connection.query("SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'MY_ERR';", function (err, rows) {
  console.log(JSON.stringify(err));
/*
{"code":"ER_SIGNAL_EXCEPTION","errno":1644,"sqlMessage":"MY_ERR","sqlState":"45000","index":0,"sql":"SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'MY_ERR';"}
*/
});
```

### CODE REVIEW

**Comment by sidorares** [comment]
Thanks @williamdes !

**Comment by williamdes** [comment]
You're welcome @sidorares :)

**Comment by sidorares** [comment]
I noticed there is also small difference in how we treat `sqlState`, would be great to align with mysqljs/mysql. Would you be able to look at this as well? ( ideally with updated test + package.json minor version bump + line in changelog if I'm not asking too much )

**Comment by williamdes** [comment]
Did a pull request #667 
I hope I did it like you expected :)

The promise way of doing a request returns message and not sqlMessage in an error. Should I change the name to ```sqlMessage``` ?

**Pull request merged**
