### PR TITLE
More complete way of adding typings for the `Server` module

### PR DESCRIPTION
**Pull request by jmordica**
- Conformed to the way typings are being added currently in the project
- Fixed an issue importing `PrepareStatementInfo` (while we're at it)

### CODE REVIEW

**Comment by sidorares** [comment]
not sure why https://github.com/sidorares/node-mysql2/actions/workflows/code-coverage.yml is still failing, I disabled in manually

Could you add some typings unit tests for types covered in this pr? ( And perhaps ones discussed in https://github.com/sidorares/node-mysql2/pull/1584#issuecomment-1210935539 )

**Comment by jmordica** [comment]
Looks like checks are failing because the package-lock.json isn't synced with the package.json. I can `npm install` and add the `package-lock.json`

**Comment by jmordica** [comment]
Now that the actual errors are fixed related to typings, i'll add the test for the Server typings.

**Comment by jmordica** [comment]
@sidorares I've added a new test environment for typings specifically and went ahead and included the `Server` module. So going forward, anyone that creates new typings will be encouraged to add a test in `typings/test` and modify the `tests.json`.

Let me know if this seems over-engineered or if you have any questions. Based on your response, I can also add proper tests for the changes in PR #1584.

**Pull request merged**
