### PR TITLE
Make node-mysql2 compatible with minification

### PR DESCRIPTION
**Pull request by BarthesSimpson**
Fixes https://github.com/sidorares/node-mysql2/issues/890

I tried to create some automated tests for this in the package itself, but that was too hard without bringing in a bunch of dependencies that don't belong in here. So, I just tested it by creating a minimal application that imports my fork of node-mysql2, establishes a connection to a local MySQL instance, and queries a table.

This may not work with all minification libraries or bundlers, but it works with webpack and a minimal babel config that just uses the env preset.

### CODE REVIEW

**Comment by sidorares** [comment]
Thanks @BarthesSimpson !

**Comment by cbschuld** [comment]
@sidorares @BarthesSimpson - thanks!  this is a cool update; I am unfamiliar in your release cadence; any insight into when this update may arrive into a release?

**Comment by jp928** [comment]
Looking forward for this in next release too.

**Comment by brokentone** [comment]
I also just hit this issue and am looking forward for the release!

**Comment by jp928** [comment]
@sidorares 
are we waiting for something else? it has been 23 days passed.

**Comment by sidorares** [comment]
hey all, sorry it took so long, published as v1.7.0 - please let me know if you have any issues

**Comment by m-noda-da** [comment]
@sidorares @BarthesSimpson 
>This may not work with all minification libraries or bundlers, but it works with webpack and a minimal babel config that just uses the env preset.

Hi, I want to use mysql2(v1.7.0) with webpack minification but I get the error like berow.
```
TypeError: Cannot read property 'fromPacket' of undefined
    at N.handshakeInit (<...>/node_modules/mysql2/lib/commands/client_handshake.js:92:40)
    at N.execute (<...>/node_modules/mysql2/lib/commands/command.js:39:22)
    at R.handlePacket (<...>/node_modules/mysql2/lib/connection.js:408:32)
    at n.onPacket (<...>/node_modules/mysql2/lib/connection.js:70:12)
    at n.executeStart <...>/node_modules/mysql2/lib/packet_parser.js:75:16)
```

Is there a way to make it compatible with webpack minification ?

**Comment by mp3por** [comment]
Hello, I get the same error. as @m-noda-da. Please fix this.

**Comment by sherry9872** [comment]
Hello ,
Getting the below error 
TypeError: Packets.HandshakeResponse is not a constructor

Any inputs

**Pull request merged**
