### PR TITLE
release idle connnections after timeout

### PR DESCRIPTION
**Pull request by qingyang-id**

### CODE REVIEW

**Comment by ouraios** [comment]
@yqsailor Checks failed on linting apparently, can you check that ? maybe that way it'll be reviewed, (im looking for that feature too)

**Comment by ouraios** [comment]
@sidorares can you check this PR and do a a review of it ? having an idle timeout on this amazing package would make it a perfect package in every sense !

**Comment by fengwanqing** [comment]
great~

**Comment by yqsailor** [comment]
hello guys, any update of this? Wish you to build a release about this, so that we can upgrade this version to our production.

**Comment by xpiREC** [comment]
@sidorares Any proceeding, I would gladly use this option in my environment.

**Comment by SkipHendriks** [comment]
@sidorares I would like to use this in my project. Any chance of this getting merged / fixed. Seems to be a test coverage issue, but the logs have been cleaned up already. Wouldn't mind to help out if that increases the chance of this PR getting merged.

**Comment by qingyang-id** [comment]
@sidorares I've synced the latest master code, may be the test coverage can be passed this time, can you help take a look?

**Comment by vlasky** [comment]
@sidorares any further changes needed to get this PR for "release idle connnections after timeout" over the line?

**Comment by sidorares** [comment]
@vlasky nothing in particular, the change LGTM

for some reason don't see CI run here, it might have been created before migration to GH actions
@qingyang-id  could you rebase? or maybe @vlasky you can try this branch locally (or re-create PR from this branch and see how tests go)

**Comment by qingyang-id** [comment]
will resubmit a new pr for this feature

**Comment by qingyang-id** [comment]
The new pr link: https://github.com/sidorares/node-mysql2/pull/1790

**Pull request closed without merging**
