### PR TITLE
Always cancel connect timeout

### PR DESCRIPTION
**Pull request by evanskinner**

### CODE REVIEW

**Comment by sidorares** [comment]
Looks good to me. Could you add a test for this? Prob use fake server and cut connection

**Comment by evanskinner** [comment]
@sidorares Test now added. Without the fix in connection.js the test registers the connection closed error and then hangs for 10 seconds before throwing ETIMEDOUT. With the fix in connection.js the test completes quickly and just registers the connection closed error.

**Comment by SpenserJ** [comment]
@sidorares Do you have any update on this? I'm running into this issue when my code attempts to connect to the database while it is starting up (server closes the connection because it isn't ready), and the timeout still fires even though I've received the exception and handled it.

The exception that I'm receiving and handling is being sent from [`this.stream.on('close', ...)`](https://github.com/sidorares/node-mysql2/blob/v2.1.0/lib/connection.js#L84-L98), and after applying this patch with Yarn, the issue is no longer occurring.

**Comment by sidorares** [comment]
@SpenserJ @evanskinner somehow missed update here. I'll prepare release to npm later this week

**Comment by vlasky** [comment]
@sidorares eagerly awaiting the release of the NPM with this uncatchable timeout exception fix! :-)

**Pull request merged**
