### PR TITLE
chore(*): move to let/const

### PR DESCRIPTION
**Pull request by SimonSchick**
*IMPORTANT: VIEW WITHOUT WHITESPACE CHANGES*

This does a few things:
1) Convert all usage of `var` to `let/const`
2) Beef up eslint rules to ensure the proper implementation of the former
3) Enabled strict mode (has to do with iteration in for in loops)
4) Remove dead code
5) Fixed some broken code (see `REVIEW` comments).
6) Emit some `warn` events when also logging to console.

Please note that tests are failing right now, I noticed a dead loop inside of a test that I fixed, please see the build log for explanation.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Please also note that I only enabled lint rules that I deemed necessary, primarily finding unused and undefined references and definition order.

**Comment by SimonSchick** [comment]
If this PR is too big I can break it down into multiple chunks (per folder).

**Comment by sidorares** [comment]
looks like there are some real test failures, not just lint or something. Have you tried investigating them @SimonSchick ? Do you need any help?

**Comment by SimonSchick** [comment]
Fixed the `test-auth-switch` test failure, I accidently removed a marker read when removing unused variables, restored that now.

**Comment by SimonSchick** [comment]
ping

**Comment by SimonSchick** [comment]
@sidorares hi

**Comment by sidorares** [comment]
hi @SimonSchick sorry, terribly busy last few weeks

we need to fix failing tests / conflicts to be able to merge. CI is still failing

**Comment by SimonSchick** [comment]
I specifically asked you to look at the the failing test case as the test that is failing right now was previously not even running.
I will resolve the conflicts once CI passes :)

**Comment by SimonSchick** [comment]
On another note, is there a reason you execute `nvm ls-remote` in travis? Seems to serve no purpose but slow down builds.

**Comment by sidorares** [comment]
> On another note, is there a reason you execute nvm ls-remote in travis? Seems to serve no purpose but slow down builds.

we can remove that, was trying to debug node version issue long time ago

**Comment by SimonSchick** [comment]
Rebased and removed the redundant version printing.

**Comment by SimonSchick** [comment]
Hey @sidorares had any time to look at that failing test? Otherwise I will comment out the failing test.

**Comment by SimonSchick** [comment]
done

**Comment by SimonSchick** [comment]
done

**Comment by SimonSchick** [comment]
done

**Comment by sidorares** [comment]
looks my issues were related to GH outage today. I'll try to re-trigger CI now

**Comment by sidorares** [comment]
looks my issues were related to GH outage today. I'll try to re-trigger CI now

**Comment by SimonSchick** [comment]
done

**Comment by SimonSchick** [comment]
Sorry for the comment spam, the outage was/is pretty bad lol.

**Comment by SimonSchick** [comment]
I added your changed but reworded the commits (force push), doesn't seem like they are showing up correctly tho.

**Comment by SimonSchick** [comment]
It's working! 😄

**Comment by sidorares** [comment]
Huh, finally it's there. Thanks for your work @SimonSchick and sorry it took so long time, last month was super busy for me

**Pull request merged**
