### PR TITLE
added clearing of "connectionTimeout" in _handleNetworkError

### PR DESCRIPTION
**Pull request by jacobbogers**
put in fix to clear connectionTimeout

### CODE REVIEW

**Comment by jacobbogers** [comment]
Please let me know if this is good enough for a merge, thanks

**Comment by sidorares** [comment]
All good, thanks!

**Comment by jacobbogers** [comment]
Thanks @sidorares , there is some urgency to have this fix in my project, is it possible to make a minor release on npm?
Excuse, I forgot to make add to changelog, I will make seperate PR for that

**Comment by sidorares** [comment]
@jacobbogers I'll publish today (in the next 2-4 hours)

**Pull request merged**
