### PR TITLE
fix: handshake SSL error with AWS RDS

### LINKED ISSUE #2581: HANDSHAKE_SSL_ERROR with RDS and 3.9.3+
using mysql2 with AWS nodejs lambdas and AWS RDS.

As of March 2024, our RDS instance was still on the 2019 certificate bundle.  Versions of mysql2 <3.9.3 were working fine with calls to createConnection.  We updated a project to 3.9.3 and started getting these errors:

{"errorType":"Error","errorMessage":"unable to get local issuer certificate","code":"HANDSHAKE_SSL_ERROR","message":"unable to get local issuer certificate","stack":["Error: unable to get local issuer certificate","    at fn (/private/var/folders/48/8n9w9qzn17s1gpq7tjs3cnv40000gp/T/tmplakzpggq/node_modules/mysql2/promise.js:253:31)

I noticed the reference to https://github.com/sidorares/node-mysql2/pull/2131 and instructed my team to update the mysql certificate bundle so we could retest.  We updated RDS to bundle rds-ca-rsa2048-g1.   Trying mysql2 3.9.3 gives the same error.

I noticed the mysql2 issue: https://github.com/sidorares/node-mysql2/pull/2542 regarding the certificates and waited for the fix and for 3.9.4.  We have tried again with 3.9.4 and get the same error on calls to createConnection.

If anyone is successfully using this package 3.9.3 or 3.9.4 with RDS, please let me know what steps are required to get past this error.  Thanks!

### PR DESCRIPTION
**Pull request by wellwelwel**
Closes #2581.

---

This _PR_ deprecates the `ssl: 'Amazon RDS'` and uses the certificate bundle from [**aws-ssl-profiles**](https://github.com/mysqljs/aws-ssl-profiles) dependency.  
The documentation has been updated to suggest installing [**aws-ssl-profiles**](https://www.npmjs.com/package/aws-ssl-profiles) for **AWS RDS** certificates.  

> @MarioRomanDono, thanks again for the proxy bundle 🙋🏻‍♂️

---

```js
'use strict';

const awsCaBundle = require('aws-ssl-profiles');

/**
 * @deprecated
 * Please, use [**aws-ssl-profiles**](https://github.com/mysqljs/aws-ssl-profiles).
 */
exports['Amazon RDS'] = {
  ca: awsCaBundle.ca,
};
```

---

> [!note]
> 
> ☔️ The coverage percentage was affected by removing the amount of previous lines from string certificates (~2,877 lines removed).

### CODE REVIEW

**Comment by sidorares** [comment]
LGTM, thanks @wellwelwel !

**Review by sidorares — APPROVED** [review]

**Comment by mrajasekar-godaddy** [comment]
Hi @sidorares Has this fix been published yet ? Currently I'm using _promise-mysql_ which is a wrapper function of mysqljs

Currently when I use ssl: awsCaBundle to pull in the new cert then I am getting the following error:

"error": {
    "message": "ER_BAD_FIELD_ERROR: Unknown column 'PJ.tier' in 'field list'",
    "code": "ER_BAD_FIELD_ERROR",
    "detail": null,
    "stack": "Error: ER_BAD_FIELD_ERROR: Unknown column 'PJ.tier' in 'field list'\n    
"}"

And this is not related to the codebase. Is there something which I am doing here is wrong 

Our config `return {
      host: process.env.DBHOST,
      port: process.env.DBPORT,
      user: process.env.DBUSER,
      password: process.env.DBPASSWORD,
      connectTimeout: 3000,
      timezone: 'Z',
      ssl: awsCaBundle
      }`

**Comment by wellwelwel** [comment]
Hi @mrajasekar-godaddy, can you perform a basic test?

Instead of:

```js
{
  ssl: awsCaBundle,
}
```

Try:

```js
{
  ssl: {
    ca: awsCaBundle.ca,
  }
}
```

I'm a bit uncomfortable with the import approach, for example:

```js
import awsCaBundle from 'aws-ssl-profiles';

console.log(Object.getOwnPropertyNames(awsCaBundle));
// -> [ 'ca', 'proxyBundle' ]
```

> By use it as `{ ssl: awsCaBundle }`, we aren't only passing on `ca`, but also all the modules available in the import _(not sure if this is related, btw)_.

**Comment by mrajasekar-godaddy** [comment]
Hi @wellwelwel, Thank you for the quick response. Sure will do test it 

Got it. Agree with your thought on using the import approach, that wouldn't be ideal to use. Will test out the suggestion and let you know.  

`
{
 ssl: {
  ca: awsCaBundle.ca,
  }
 }
`

**Comment by mrajasekar-godaddy** [comment]
Hi @wellwelwel 

I did try using this `{ ssl: { ca: awsCaBundle.ca, } }` but it still does't work and I am seeing the same error. Is there any other possible ways I can try it. It seems to not refer to the ca cert.

Thanks in Advance

**Comment by wellwelwel** [comment]
> I did try using this `{ ssl: { ca: awsCaBundle.ca, } }` but it still does't work and I am seeing the same error. Is there any other possible ways I can try it. It seems to not refer to the ca cert.

Hey @mrajasekar-godaddy, in that case, I recommend you to [open an issue](https://github.com/sidorares/node-mysql2/issues/new).

If possible, share a minimal reproduction 🙋🏻‍♂️

**Comment by mrajasekar-godaddy** [comment]
Thank you for the quick response. Submitted an issue here [https://github.com/sidorares/node-mysql2/issues/2869]

**Comment by mrajasekar-godaddy** [comment]
Added steps for reproduction. It would be great, if we could even schedule a call if that works.

My observations ( if this would help by any chance ):

1. ssl: expects a string `Amazon RDS` , but when we supply `ssl: awsCaBunlde` it doesn't accpet it, as awsCaBunle is an object

2. Also, when we supply as `{ ssl: { ca: awsCaBunlde.ca } } ` it won't work either. as ca option does expect string. 

Thanks again

**Comment by mrajasekar-godaddy** [comment]
@wellwelwel Hi, I was able to connect to SSL finally. Thank you for the support and the help

Huge thanks to all the folks who contributed to creating this library.

**Pull request merged**
