### PR TITLE
ci: fix test file name

### PR DESCRIPTION
**Pull request by wellwelwel**
Fixes:

Screenshot 2024-03-26 at 02 51 43

### CODE REVIEW

**Comment by sidorares** [comment]
unrelated, but it's probably time to drop node 14.x and 16.x from the matrix

**Comment by wellwelwel** [comment]
> unrelated, but it's probably time to drop node 14.x and 16.x from the matrix

I'll open a new PR for this 🙋🏻‍♂️

---

Also, @sidorares, can you check the Codecov app? It's actually warning:

```
❗ Your organization needs to install the Codecov GitHub app to enable full functionality.
```

**Comment by sidorares** [comment]
I clicked "install", not sure where this is visible i codecov settings. I guess we'll validate this in the next codecov report comment

**Comment by wellwelwel** [comment]
> I clicked "install", not sure where this is visible i codecov settings. I guess we'll validate this in the next codecov report comment

It worked now 🎉

Screenshot 2024-03-26 at 03 33 08

**Pull request merged**
