### PR TITLE
fix: sql-template-strings compatibility

### PR DESCRIPTION
**Pull request by BauerPh**
this should fix issue #2192.

tested with Promise wrapper and Pools only

### CODE REVIEW

**Comment by BauerPh** [comment]
> thanks @BauerPh ! Could you check unit tests locally?

I'll try, but im not a pro xD

**Comment by BauerPh** [comment]
okay: tests should pass now.
But i don't know if that is a good solution but it works now with the sql-template-tag & sql-template-strings library.

**Comment by sidorares** [comment]
why do you need to detect that? Can this

```js
{
          ...options,
          sql: sql.sql,
          values: sql.values,
        };
```
work for both scenarios?

**Comment by BauerPh** [comment]
yeah, it was stupid :D

Problem:

```JS
{
  ...options,
  sql: sql.sql,
  values: sql.values
};
```
omits other options passed through the `sql` parameter, like `namedPlaceholders` => tests fail.

```
options = {
  ...options,
  ...sql,
  sql: sql.sql
};
```
should finally do it.

**Comment by sidorares** [comment]
lgtm, thanks @BauerPh !

**Comment by sidorares** [comment]
should be released to npm as v3.6.2 in a moment. When you have time could you try with the version from npm and close original issue if everything works well for you @BauerPh ?

**Pull request merged**
