### PR TITLE
added tests and fixes for #1546

### PR DESCRIPTION
**Pull request by stevemandl**

### CODE REVIEW

**Comment by sidorares** [comment]
hi @stevemandl could you cherry-pick b96364e51b69344b0c4a0cc0ccf6b2dde27c6466 into your PR? that commit fixes CI that started to break for timestamp tests after one of the mysql server version bump in the build matrix

**Comment by stevemandl** [comment]
cherry-pick is done

**Comment by sidorares** [comment]
few assertions in others tests need to be updated to add `type`

**Comment by sidorares** [comment]
thanks @stevemandl !

**Pull request merged**
