### PR TITLE
Fix typo in Promise Wrapper section in README.md 

### LINKED ISSUE #816: Erro in Promise Wrapper section example in README.md
I copy and pasted the example below in a plain js file in project and when I run the file with node I get error "TypeError: pool.promise is not a function".

mysql2 version installed with npm 1.5.3
node 8.11.2
mysql 5.7.20

MySQL2 also exposes a .promise() function on Pools, so you can create a promise/non-promise connections from the same pool
```js
async function main() {
  // get the client
  const mysql = require('mysql2');
  // create the pool
  const pool = mysql.createPool({host:'localhost', user: 'root', database: 'test'});
  // now get a Promise wrapped instance of that pool
  const promisePool = pool.promise();
  // query database using promises
  const [rows,fields] = await promisePool.query("SELECT 1");
```

### PR DESCRIPTION
**Pull request by realphi**
Fixes #816

### CODE REVIEW

**Comment by sidorares** [comment]
I think you misread documentation. This has just been added recently, and this is a way to "upgrade" _non-promise_ pool/connection to promise one

**Comment by realphi** [comment]
The part you mentioned is below this part. I copy pasted the example and node exited with "TypeError: pool.promise is not a function" and I tried requiring mysql2/promise and it fixed it.

**Comment by realphi** [comment]
Seems this didn't fix my problem either:|

**Comment by sidorares** [comment]
still not very clear what problem you having. Can you describe 1) version of the library ( npm version or commit if you install from git ) 2) node version 3) mysl server version 4) expected behavior 5) actual behavior

**Comment by realphi** [comment]
Sorry, I will continue this discussion in the issue.

**Comment by sidorares** [comment]
sure!

**Pull request closed without merging**
