### PR TITLE
Add configurable logging capability to connection

### PR DESCRIPTION
**Pull request by swftvsn**
Adds logging (configurable) to connection to diagnose missing parameters issues.

### CODE REVIEW

**Comment by sidorares** [comment]
maybe this should go to debug log ( when `debug` flag is true ) , perhaps using https://www.npmjs.com/package/debug ? I don't want to pass all possible logging options via main api

**Comment by swftvsn** [comment]
Actually the best solution would be just to have a failsafe catch, that would catch any errors and exceptions and log those + the current SQL + values. I'm just unsure of the correct location to add this. First I thought it would be connection.execute, but due to the async nature I'm not sure if catch there would actually catch anything. What do you think @sidorares

**Comment by sidorares** [comment]
try/catch used to be performance killer, maybe we should add more of those even to guard against internal code problems. To direct that particular error callback you'd need try/catch around https://github.com/sidorares/node-mysql2/blob/5f65614a0d61e4ea23d6b1ce0f75548205ba49f7/lib/commands/execute.js#L48 and call `this.onResult(error)` in catch block

**Comment by swftvsn** [comment]
I see what you mean. I've added a try-catch wrap to PR #689, but if try is performance hazard, maybe we should pass the callback down to all *.toPacket methods so errors could be dealt with there. This, however is a big change, so I'll not prepare a PR for that. I'm happy with the fix in #689, so if it's ok to add that, please go ahead and merge and release.

It would fix these things: (all symptoms of the same problem, which actually is bad input, but this makes the library more developer friendly by informing the dev better what the problem is)
1. #493
2. #187
3. #480

**Comment by sidorares** [comment]
we have early error reporting on missing parameters now, closing this

**Pull request closed without merging**
