### PR TITLE
fix Query.stream exception on prepared statements

### PR DESCRIPTION
**Pull request by danieljuhl**
Related to #174 but for prepared statements

### CODE REVIEW

**Comment by danieljuhl** [comment]
@sidorares any idea when you can make a new release?

**Comment by sidorares** [comment]
50% probability - now before I fall asleep, but if not - in 8 hours :)

**Comment by danieljuhl** [comment]
Perfect, Thanks!

**Comment by danieljuhl** [comment]
Sorry to bother you again :) - probability that we get a release today?

**Comment by sushantdhiman** [comment]
@danieljuhl You can use master branch in your `package.json` directly

**Comment by sidorares** [comment]
@danieljuhl sorry was hoping to quickly finish https://github.com/sidorares/node-mysql2/pull/418#issuecomment-251302237 but still not. Will do that later

publishing now current master as v1.1.1

**Comment by sidorares** [comment]
v1.1.1 on npm

**Comment by danieljuhl** [comment]
Thanks!

**Pull request merged**
