### PR TITLE
[Amazon RDS] Update to 2019 CA certificates

### PR DESCRIPTION
**Pull request by JorgenEvens**
Amazon released new (2019) CA certificates for Amazon RDS.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

Updated to use https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem (for Amazon RDS)
and https://www.amazontrust.com/repository/AmazonRootCA1.pem (AWS Serverless Aurora)

### CODE REVIEW

**Comment by sidorares** [comment]
Thanks @JorgenEvens !

**Comment by JorgenEvens** [comment]
HI @sidorares,

I hate that I have to bother with this, but do you have a date on when this would hit a release? Amazon's wording in their e-mail suggests we'd need to replace the certificates soon (see below), but I'd hate to upgrade our production services to an `-alpha` release.

> Please act before October 31, 2019 to address an upcoming interruption of your applications using RDS and Aurora database instances.

**Comment by sidorares** [comment]
Hi @JorgenEvens I'll try to publish v2.0 release today

**Comment by sidorares** [comment]
Also - nothing stops you from using certs from your own config, "Amazon RDS" bundle option is just for convenience

**Comment by sidorares** [comment]
@JorgenEvens v2.0.0 release is published

**Comment by JorgenEvens** [comment]
@sidorares Thanks, that is great news!

**Pull request merged**
