### PR TITLE
Updating RDS ssl cert for 1.x release.

### PR DESCRIPTION
**Pull request by jhoscar1**
Not sure where to base this PR against this repo given that 1.x can't be released from master and there's no 1.x branch. Perhaps I'm missing something?

Responding to #1117

### CODE REVIEW

**Comment by sidorares** [comment]
Can you rebase it off https://github.com/sidorares/node-mysql2/releases/tag/v1.6.5 ?

**Comment by jhoscar1** [comment]
@sidorares Unfortunately, you can't base a PR against a tag or at least Github isn't allowing me to do so. Could you maybe make a branch based on that tag, perhaps called `1.x` and then I'll base this PR against that branch?

**Comment by charlie-s** [comment]
Thanks for taking the time to handle this, @jhoscar1, and thank @sidorares for accepting so quickly. We're looking to deploy this tomorrow evening on staging servers.

**Comment by sidorares** [comment]
@jhoscar1 I created `v1.x` branch based off  821b2bcdc254c483e6879b5d4afc9757c55c7ed7

https://github.com/sidorares/node-mysql2/tree/v1.x

**Comment by jhoscar1** [comment]
@sidorares Thank you! Rebased the PR

**Comment by sidorares** [comment]
@jhoscar1 published as `v1.6.6`

**Pull request merged**
