### PR TITLE
fix #932

### LINKED ISSUE #932: Error in Promise Wrapper section in README, with a question that how to check whether success or not after connecting to databse
In README,there is one code which has problem,see below:
```js
async function main() {
  // get the client
  const mysql = require('mysql2');
  // create the connection
  mysql.createConnection(
   {host:'localhost', user: 'root', database: 'test'},
   (err,con) => {
    con.promise().query("SELECT 1")
    .then( ([rows,fields]) => {
     console.log(rows);
    })
    .catch(console.log)
    .then( () => con.end());
   }
  );
```
I tried this, but can't go to callback.Then I check out the source code, find there is no second arguments in `createConnection`.If so, how can I check whether success or not after connecting to databse?

### PR DESCRIPTION
**Pull request by meloseven**
fix #932

### CODE REVIEW

**Comment by sidorares** [comment]
I think you lost closing `}` matching 'async function main() {`. Maby better to remove `async function main() {` from example altogether as it's not using async/await?

**Comment by meloseven** [comment]
Sorry, let me modify it.

**Comment by sidorares** [comment]
sorry for nits but I'd really like for this change to result in example that can me almost copy pasted, and in your version `con` is undefined, should be something like `const connection = mysql.createConnection({host:'localhost', user: 'root', database: 'test'})`; con.promise().query("SELECT 1").then(...)`

**Comment by meloseven** [comment]
I'm terribly sorry.

**Comment by sidorares** [comment]
Thanks @meloseven !

**Pull request merged**
