### PR TITLE
use bluebird instead of es6-promise

### PR DESCRIPTION
**Pull request by thewillhuang**
because this is a fast lib, it should use a fast promise implimentation

### CODE REVIEW

**Comment by sidorares** [comment]
this looks more like a documentation / defaults improvement. Maybe we should put more words into https://github.com/sidorares/node-mysql2#using-promise-wrapper and https://github.com/sidorares/node-mysql2/blob/master/documentation/Promise-Wrapper.md ?

Also, do you suggest this because bluebird is considered fast or you have your own benchmark and experience using mysql2 with bluebird vs native promises or some other library? If so, can you share some of your benchmark numbers? I would expect bluebird to perform faster as well, but would be good to see some real life numbers. Also for me only reason to have promises is async/await and in that case I think I'm forced to use native Promise

**Comment by thewillhuang** [comment]
sure thing! Here are some recent benchmark results. At the minimum, it's 2-5x faster than native V8 promise implementation for these micro benchmakrs.

I believe having a pretty good default is a good thing overall.

```
NODE_ENV=production ./bench doxbee
results for 10000 parallel executions, 1 ms per I/O op

file                                       time(ms)  memory(MB)
callbacks-baseline.js                            90       24.33
callbacks-suguru03-neo-async-waterfall.js       154       38.20
promises-bluebird-generator.js                  202       39.79
promises-bluebird.js                            215       47.27
promises-then-promise.js                        282       67.96
promises-cujojs-when.js                         288       64.13
promises-lvivski-davy.js                        368       86.20
promises-tildeio-rsvp.js                        375       89.95
callbacks-caolan-async-waterfall.js             471      101.82
promises-dfilatov-vow.js                        565      133.06
promises-calvinmetcalf-lie.js                   655      163.72
generators-tj-co.js                             886      148.49
promises-obvious-kew.js                         977      109.27
promises-ecmascript6-native.js                 1021      146.50
promises-medikoo-deferred.js                   1531      146.70
observables-Reactive-Extensions-RxJS.js        1676      251.66
streamline-generators.js                       1801      134.55
streamline-callbacks.js                        2903      211.04
promises-kriskowal-q.js                        9286      450.03
observables-baconjs-bacon.js.js               18269      823.59
observables-pozadi-kefir.js                   32771      162.81
observables-caolan-highland.js                63962      515.93

Platform info:
Darwin 16.4.0 x64
Node.JS 6.10.1
V8 5.1.281.95
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz × 8
```
```
NODE_ENV=production ./bench doxbee
results for 10000 parallel executions, 1 ms per I/O op

file                                       time(ms)  memory(MB)
callbacks-baseline.js                           110       24.87
callbacks-suguru03-neo-async-waterfall.js       157       36.60
promises-bluebird-generator.js                  230       38.77
promises-bluebird.js                            285       47.58
promises-cujojs-when.js                         397       70.58
promises-lvivski-davy.js                        444       95.41
promises-then-promise.js                        449       82.13
promises-tildeio-rsvp.js                        481       80.51
callbacks-caolan-async-waterfall.js             612      103.99
promises-dfilatov-vow.js                        677      136.98
promises-calvinmetcalf-lie.js                   797      162.21
generators-tj-co.js                             858      120.50
promises-ecmascript6-native.js                  959      166.79
promises-obvious-kew.js                        1004      214.17
observables-pozadi-kefir.js                    1310      188.56
promises-medikoo-deferred.js                   1313      185.27
observables-Reactive-Extensions-RxJS.js        2023      183.50
streamline-generators.js                       2477      127.88
observables-caolan-highland.js                 6304      514.50
promises-kriskowal-q.js                        6605      387.43
observables-baconjs-bacon.js.js               20183      813.96
streamline-callbacks.js                       25611      204.35

Platform info:
Darwin 16.4.0 x64
Node.JS 7.8.0
V8 5.5.372.43
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz × 8
```
```
NODE_ENV=production ./bench parallel
results for 10000 parallel executions, 1 ms per I/O op

file                                      time(ms)  memory(MB)
callbacks-baseline.js                          214       68.19
callbacks-suguru03-neo-async-parallel.js       346       81.84
promises-bluebird.js                           393      101.03
promises-bluebird-generator.js                 473      106.49
promises-lvivski-davy.js                       583      165.32
promises-cujojs-when.js                        670      165.96
callbacks-caolan-async-parallel.js             716      150.78
promises-tildeio-rsvp.js                      1409      353.38
promises-then-promise.js                      1447      313.74
promises-calvinmetcalf-lie.js                 1459      378.24
promises-ecmascript6-native.js                2270      450.61
promises-dfilatov-vow.js                      2436      535.62
promises-medikoo-deferred.js                  3849      389.17
promises-obvious-kew.js                       4092      754.55
streamline-generators.js                     17688     1206.85
streamline-callbacks.js                      33175     1303.73

Platform info:
Darwin 16.4.0 x64
Node.JS 6.10.1
V8 5.1.281.95
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz × 8
```
```
NODE_ENV=production ./bench parallel
results for 10000 parallel executions, 1 ms per I/O op

file                                      time(ms)  memory(MB)
callbacks-baseline.js                          380       72.05
callbacks-suguru03-neo-async-parallel.js       451       87.40
promises-bluebird.js                           704      103.75
promises-bluebird-generator.js                 753      107.52
promises-lvivski-davy.js                       773      167.25
callbacks-caolan-async-parallel.js             927      151.26
promises-cujojs-when.js                       1013      167.59
promises-then-promise.js                      1527      310.40
promises-tildeio-rsvp.js                      1706      368.81
promises-calvinmetcalf-lie.js                 2204      382.85
promises-ecmascript6-native.js                2654      395.07
promises-medikoo-deferred.js                  3055      373.88
promises-dfilatov-vow.js                      3297      558.31
promises-obvious-kew.js                       4634      683.54
streamline-generators.js                     19340     1099.41
streamline-callbacks.js                      33970     1205.56

Platform info:
Darwin 16.4.0 x64
Node.JS 7.8.0
V8 5.5.372.43
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz × 8
```

**Comment by dougwilson** [comment]
I think the question was benchmarks for this module with and without the change. I can't see how this will make any difference on Node.js > 0.10, because global.Promise will be defined already and bluebird will not be used.

**Comment by thewillhuang** [comment]
true, but why even pick es-promise over bluebird?

**Comment by sidorares** [comment]
> but why even pick es-promise over bluebird?

not sure exactly why I used `es-promise` as polyfill, I think it looked more standard compliant to me

maybe worth adding some useful error message if bluebird is not defined, something like 'Your runtime does not have global Promise and fall back to bluebird didn't work either. Try to install it with "npm install bluebird"'

**Comment by thewillhuang** [comment]
I opted to just throw an error to the users if there is no `opts.Promise` or `global.Promise`. This should drop the error of `es6-promise not installed` for users that want to bundle their apps via Webpack for AWS Lambda

**Comment by victor0801x** [comment]
I have a different point. using native is best way. Unless you need full promise/a+ feature.
now node >= 7.6 (v8 5.5) async/await is not optimization version.
in the future(maybe node 8?), it will improvement  (see https://v8project.blogspot.tw/2017/02/v8-release-57.html?m=1)
and I modify some benchmark for client side
 https://jsperf.com/bluebird-vs-rsvp/116

**Comment by sidorares** [comment]
@victor0801x it's native by default, discussion was more about `es6-promise` vs `bluebird` as fallback / documentation suggestion

**Pull request merged**
