### PR TITLE
Bun support

### PR DESCRIPTION
**Pull request by sidorares**
https://github.com/sidorares/node-mysql2/issues/1801

- [x] add Bun to CI
- [x] fix `caching_sha2_password` errors
- [ ] work around missing `net.createServer` by using `Bun.listen`
- [ ] compressed protocol bun fixes
- [ ] TLS bun fixes

( going to track last 3 items separately )

### CODE REVIEW

**Comment by Djboy08** [comment]
Do I have to wait for this to show up in a release to use?

**Comment by wellwelwel** [comment]
@Djboy08, it was merged in Jan, naturally it has already been released. I suggest you open a Issue indicating this problem and, if possible, share a minimal way to reproduce your problem 🙋🏻‍♂️

**Comment by Djboy08** [comment]
> @Djboy08, it was merged in Jan, naturally it has already been released. I suggest you open a Issue indicating this problem and, if possible, share a minimal way to reproduce your problem 🙋🏻‍♂️

Gotcha, the reason i brought it up was because he recently edited it saying he completed the TLS part 2 weeks ago so I was not sure why it took so long for him to update this. 

Sadly I don't really have the time right now to create a issue but Ill see what I can do when I have time. Because at the end of the day this is literally just how planetscale requires `?ssl={"rejectUnauthorized":true}` in the url and for some reason the mysql2 driver with bun just does not work with it.

**Comment by sidorares** [comment]
@Dieken thanks for the report, I'll have a look. I actually only tested with planetscale, not sure what has changed since

**Pull request merged**
