### PR TITLE
chore: apply modern code styles

### PR DESCRIPTION
**Pull request by SimonSchick**
Hi again!

This PR applies the following rules:

```
    "template-curly-spacing": ["error", "never"],
    "prefer-template": "error",
    "no-useless-call": "error",
    "no-lonely-if": "error",
    "indent": ["error", 2, {
      "SwitchCase": 1
    }],
    "no-else-return": ["error", {
      "allowElseIf": false
    }],
    "eqeqeq": "error",
```

Diff is a little bit but the changes are very straight forward.

There should be no breaking changes as 99% of the changes were automated.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Little update:
 - Resolved a tiny todo related to buffer compare
 - replaced all usage of `module.exports` with `exports` where appropriate.

**Comment by SimonSchick** [comment]
@sidorares poke

**Comment by SimonSchick** [comment]
@sidorares poke2 😛

**Comment by sidorares** [comment]
lI think it looks good :)

**Comment by sidorares** [comment]
Only took me 132 days

**Comment by sidorares** [comment]
@SimonSchick build failed after merge, I wonder how it passed initially: https://ci.appveyor.com/project/sidorares/node-mysql2/builds/23523781/job/28225stswp1ah0xg

**Comment by SimonSchick** [comment]
@sidorares you probably merged something intermediately, should be an easy fix tho.

**Pull request merged**
