### PR TITLE
allow namedParameters for queries on pool as well

### PR DESCRIPTION
**Pull request by bitcloud**
Currently it seems, that it is not possible to use namedPlaceholders directly on the pool.
Made a small pull request to pass through the namedPlaceholders config.

### CODE REVIEW

**Comment by bitcloud** [comment]
Sorry for the commit mess. I can squash it to one commit if you want and make a new PR.

**Comment by bitcloud** [comment]
tests are working now, but the query on the pool connection takes ages. There seems to be another issue involved.

**Comment by gajus** [comment]
@bitcloud Can you please squash commits and fix the failing test case?

**Comment by bitcloud** [comment]
hey @gajus, sorry for the late response. I squashed everything in one commit now and tracked down the issue in the testcase.

There was an issue that callbacks from pooled connection queries aren't correctly passed to the query object and thus get never called.

As far as I can see, my testcase seems to be the only one that is testing parts of the pooled connection??

I fixed that one now, but you should check on that. I fixed it so the function signature stays the same. But probably it would be better to not return a query object at that place as in execute. For now it is working, but I would consider it a hack.

Was broken in #230, but could be interesting for #218 and #182 as well perhaps.

**Comment by bitcloud** [comment]
Just checked some other issues and found #270. Fixed the issues in the code you posted and have even one testcase that uses the code ;-)

The original intention was to test named parameters patch from me, but it tests that issue as well.

I don't know why they attached a noop function to the error event, i think the intention was to emit an error, because attaching a noop function doesn't make any sense -- at least none i know of.

**Comment by sidorares** [comment]
thanks! especially for #270, I'll prepare rc2 release

**Comment by bitcloud** [comment]
I just thought about the code again and think someone could just use the events instead of callbacks. Then we should check the callback before we try to invoke it, because it could be undefined.
Committed the change already.

**Pull request merged**
