### PR TITLE
Lru cache

### PR DESCRIPTION
**Pull request by sushantdhiman**

### CODE REVIEW

**Comment by sushantdhiman** [comment]
https://github.com/sidorares/node-mysql2/issues/393

**Comment by sidorares** [comment]
lgtm, good to merge if CI pass

**Comment by sushantdhiman** [comment]
docs @sidorares

**Comment by sushantdhiman** [comment]
@sidorares This will fix https://github.com/sidorares/node-mysql2/issues/393, should we also close PR https://github.com/sidorares/node-mysql2/pull/321

**Comment by sidorares** [comment]
#321 is not related, is it? all good re docs

**Comment by sushantdhiman** [comment]
Ok, I have added docs too. Its ready for merge

**Pull request merged**
