### PR TITLE
Release idle connection

### PR DESCRIPTION
**Pull request by qingyang-id**
If the connection idle time exceeds the timeout, the connection will be released automatically

### CODE REVIEW

**Comment by qingyang-id** [comment]
@silentrob  Resubmit this pr for retrigger the GH actions, all checks have passed this time, can you help merge the pr

The original pr is https://github.com/sidorares/node-mysql2/pull/1379

**Comment by sidorares** [comment]
Did you want to tag me @qingyang-id :) ?

**Comment by qingyang-id** [comment]
> Did you want to tag me @qingyang-id :) ?

Yes，Do you have the access to merge this pr? or what else do i need to do?

**Comment by sidorares** [comment]
Trying https://github.com/googleapis/release-please/tree/main#how-can-i-fix-release-notes to override generated release notes

BEGIN_COMMIT_OVERRIDE
feat: add `idleTimeout` pool config property and functionality to release idle connections on timeout
END_COMMIT_OVERRIDE

**Comment by sidorares** [comment]
> > Did you want to tag me @qingyang-id :) ?
> 
> Yes，Do you have the access to merge this pr? or what else do i need to do?

I can merge it. Moving forward I'd like to follow "[conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/)" format, every pr ends up automatically in release post / changelog and I really want as little intervention in this process as possible. Hopefully tweaks can be added via commit override comments, will test that in this PR

**Comment by sidorares** [comment]
looks like release-please does not see any "releasable units" in the pr (not sure if override counts) - https://github.com/googleapis/release-please/tree/main#release-please-bot-does-not-create-a-release-pr-why

will release with the next PR

**Pull request merged**
