### PR TITLE
typings: add ResultSetHeader

### PR DESCRIPTION
**Pull request by larshp**
closes https://github.com/sidorares/node-mysql2/issues/1212

### CODE REVIEW

**Comment by sidorares** [comment]
published as v2.2.4 ( together with #1211 )

**Comment by larshp** [comment]
I'm not seeing this change in 2.2.4, also in the git history it is after the package.json change, https://github.com/sidorares/node-mysql2/commits/master

**Comment by sidorares** [comment]
🤦 I forgot to pull locally after merging this one before publishing. It's end of a long day here in Australia

**Comment by larshp** [comment]
no worries, it can wait until tomorrow/later

**Comment by sidorares** [comment]
v.2.2.5 ( would be my record day by number of publishes )

**Comment by sidorares** [comment]
I'm really bad at prioritising things, it's usually "now" or "3 years later"

**Comment by larshp** [comment]
confirmed, working now, typescript project, thanks 👍

**Pull request merged**
