### PR TITLE
Update pool-test.js

### PR DESCRIPTION
**Pull request by ISNIT0**
`.end()` is now deprecated, converted to `.release()`

### CODE REVIEW

**Comment by sidorares** [comment]
looks like `.release()` should not be there as well
Maybe original intention in example was to show how to create pool, use it with `.query()` helper and then close _pool_

`.query()` calls release for you immediately after query is finished execution - see code here https://github.com/sidorares/node-mysql2/blob/224c74de8184f78c540f343c432c0f37986c8aea/lib/pool.js#L162

**Comment by ISNIT0** [comment]
Ahh, didn't see that in any documentation. I'll change this PR to reflect this - definitely worth having *at least* valid documentation or examples :)

**Comment by sidorares** [comment]
I'm really sorry, I thought it's `pool.query()` and in that example it's actually pool.getConnection() + connection.query() - in that case `.release()` is required and your initial change was in fact correct!

**Comment by ISNIT0** [comment]
Okay, so in this case should there be an example of `pool.query()`? I had no idea that existed!

**Comment by sidorares** [comment]
yes, won't hurt adding example here

Since I'm trying to mirror mysqljs/mysql API where possible best source of documentation is there, for example pool.query part is https://github.com/mysqljs/mysql/#pooling-connections

**Comment by sidorares** [comment]
thanks!

**Pull request merged**
