### PR TITLE
Fix #323.

### LINKED ISSUE #323: [BUG]query with ? placeholder got worng result
I tested the exact same query, mysql works well. mysql2 doesn't.
pool.query('UPDATE table SET col1=?,col2=? WHERE Id = ?', [1,'http://domain.com/?query=', 3])

It will produce `1, http://domain.com/1query=`
It replace the ? in the value instead of parameter.

But test both mysql.format and mysql2.format they out put the same. That very strange.

### PR DESCRIPTION
**Pull request by dsonet**
shouldn't format SQL twice since already did in connection.query.

### CODE REVIEW

**Comment by sidorares** [comment]
you close pool in your test before other tests finish. Maybe have test for this particular issue in own file? "test-parameters-questionmark.js" and have non-pool and scenarios there

**Comment by sidorares** [comment]
you close pool in your test before other tests finish. Maybe have test for this particular issue in own file? "test-parameters-questionmark.js" and have non-pool and scenarios there

**Comment by dsonet** [comment]
Ya I see it. I'll correct it right now.

**Comment by dsonet** [comment]
It was wrong at beginning. I didn't realized that mysql TEMPORARY table can't shared across different connection.

**Comment by sidorares** [comment]
thanks @dsonet !

**Comment by sidorares** [comment]
published as v1.0.0-rc.4

**Comment by dsonet** [comment]
That's great.

**Pull request merged**
