### PR TITLE
Add type declarations for Prepare & PrepareStatementInfo

### LINKED ISSUE #1564: Missing prepare/unprepare
Looked at the documentation at https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md when I try to run a prepared statement

```js
connection.execute('statement', (error, results) => {

});

connection.unprepare('statement');
```

I get the following error

`
 error TS2339: Property 'unprepare' does not exist on type 'Connection'.
`

The prepare method also doesn't exist

### PR DESCRIPTION
**Pull request by zordtk**
This adds type declarations for Prepare & PrepareStatementInfo and then adds prepare and unprepare to the Connection declarations. Fixed #1564

### CODE REVIEW

**Comment by sidorares** [comment]
I have to check other command interfaces but there is no `determinePacket` method in mysql2 commands, my guess is that its part that was originally in `mysqljs/mysql` typings

Also, what was the reason to remove `ConnectionConfig` interface?

**Comment by zordtk** [comment]
> Also, what was the reason to remove `ConnectionConfig` interface?

Didn't realize I did.

> I have to check other command interfaces but there is no `determinePacket` method in mysql2 commands, my guess is that its part that was originally in `mysqljs/mysql` typings

I actually copied that from the type declarations from the Query command (typings/mysql/lib/protocol/sequences/Query.d.ts)

**Comment by jmordica** [comment]
Can this get merged?

**Comment by sidorares** [comment]
> Can this get merged?

yes, thanks for the ping

**Pull request merged**
