### PR TITLE
Add geometry typecast test

### PR DESCRIPTION
**Pull request by testn**
Add addition typecast tests for geometry

### CODE REVIEW

**Comment by testn** [comment]
@sidorares any idea why geo stuff is broken in 5.7? I couldn't find any related release notes.

**Comment by sidorares** [comment]
@testn it fails at `CREATE TEMPORARY TABLE geom_test (p POINT SRID 0, g GEOMETRY NOT NULL SRID 0)` query, I assume this is newer syntax and 5.7 server does not understand it

I can't see geometry types in https://dev.mysql.com/doc/refman/5.7/en/data-types.html
( there are geometry functions though - https://dev.mysql.com/doc/refman/5.7/en/functions.html )

We could check server version and skip the test if 5.7 or earlier, or somehow feature detect via sql

**Comment by sidorares** [comment]
CI logs from my copy of your commit - https://github.com/sidorares/node-mysql2/actions/runs/3906857317/jobs/6675468924

**Comment by testn** [comment]
oh sure... let me do that

**Comment by wellwelwel** [comment]
Closing due to #2395.

Thanks, @testn 🙋🏻‍♂️

**Pull request closed without merging**
