### PR TITLE
Fix typescript PoolConnection error

### PR DESCRIPTION
**Pull request by marlonfsolis**
Fixing TypeScript error TS2320: Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection'.

### CODE REVIEW

**Comment by marlonfsolis** [comment]
This fix is for open issues:
Typing error in v3.0.0-rc1 Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection' #1722
erros with tsc #1792

**Comment by sidorares** [comment]
Thanks a lot @marlonfsolis , the fix looks good!
Couple of notes:
- would it be possible to add super simple typings smoke test? A ts script that currently fails type checks without your changes and produces no errors with
- could you please rebase & rewrite commit messages to follow https://www.conventionalcommits.org/en/v1.0.0/ ? ( this is important for release-please to automatically prepare release PR and also github release and changelog )

**Comment by marlonfsolis** [comment]
@sidorares Andrey I add a small test in existing pool.ts tests. Hope this is fine. 
I rebase and reword fallowing [Github doc](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message). Hope this is okay.
Let me know if need anything else.

**Comment by sidorares** [comment]
I'm not sure why previous commits are so different now. Can you rebase your changes to be on top of the current master? I think when you do this the "commits" tab should only show your commits

**Comment by rostalevicek** [comment]
Is there any progress? Can it be merged?

**Comment by marlonfsolis** [comment]
It seems to be fixed already in a better and more elegant way.

**Pull request closed without merging**
