### PR TITLE
Enhancement:fix handshake seed value for jdbc ascii encoding

### PR DESCRIPTION
**Pull request by piaohai**
mysql java jdbc seed encoding is ascii ,where seed encoding char larger than ascii,hand shake failed

### CODE REVIEW

**Comment by sidorares** [comment]
could you elaborate a bit more how to reproduce problem you are solving? This is server part of the protocol - can you show the client code that is accessing mysql2-based server?

**Comment by piaohai** [comment]
Server:

var mysql = require('mysql2');

var server = mysql.createServer();
server.listen(3307);
server.on('connection', function(conn) {

  console.log('connection');

  var socket = conn.stream;

  conn.serverHandshake({
    protocolVersion: 10,
    serverVersion: '5.6.10',
    connectionId: 1234,
    statusFlags: 2,
    characterSet: 8,
    capabilityFlags: 0xffffff,
    authCallback: function(params, cb){
        var pass = "helloword";
        var doubleSha = auth.doubleSha1(pass);
        var isValid = auth.verifyToken(params.authPluginData1, params.authPluginData2, params.authToken, doubleSha);
        console.log(isValid);
     }
   });
});

Client:

public class Test {

	public static void main(String[] args) throws SQLException, IOException {
 		getConnection();
		System.in.read();
	}

	public static void test() {

	}

	public static Connection getConnection() throws SQLException {
		Connection conn = null;
		Properties connectionProps = new Properties();
		connectionProps.put("user", "root");
		connectionProps.put("password", "helloword");
		try {
			Class.forName("com.mysql.jdbc.Driver");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/mysql?&autoReconnect=false&connectTimeout=5000&socketTimeout=50000",
				connectionProps);

		System.out.println("Connected to database");
		return conn;
	}

}


jdbc client connect handshake failed.

**Comment by piaohai** [comment]
threadId = buf.readLong();
this.seed = buf.readString("ASCII", getExceptionInterceptor());

mysql jdbc driver protocol read

**Comment by sidorares** [comment]
I don't think connection failure is related to how 20-bytes salt is generated. Closing this for now, if you have more specific diagnostic message pleas open another issue. I'm working on some improvements in server implementation, stay tuned for updates!

**Pull request closed without merging**
