### PR TITLE
replace deprecated Buffer apis with new API

### PR DESCRIPTION
**Pull request by sidorares**
Ref: #380

`Buffer(number)` and new `Buffer(number)` replaced with `Buffer.unsafeAlloc(number)`
`new Buffer(string)` and `new Buffer(array)` replaced with `Buffer.from`

some `new Buffer()` still left in tools and benchmarks

### CODE REVIEW

**Comment by sidorares** [comment]
@sushantdhiman would you be able to review?

**Comment by sushantdhiman** [comment]
We are using `allocUnsafe` a lot (I guess for performance), its good but we need to be sure those buffer are completely filled.

**Comment by sidorares** [comment]
yes, everywhere it's used the intention is to fill all bytes of buffer. There is one exception, in handshake packet there is 10 bytes zero filler so I'm using `Buffer.alloc(size, 0)` + `packet.skip(10)` there (instead of filling 10 bytes manually). I'll try to double check again myself. I wander maybe we could use some version of Buffer in tests that allows to check that there is no uninitialised space in resulting buffers.

**Comment by sushantdhiman** [comment]
It appears most of time `unsafeAlloc` is used to build packets or headers that are filled to the end. So it LGTM.

We might be able to add unit tests for each `Header/Packet` type and try initialize them with mock data, at the end we could inspect if `Header/Packet` was properly prepared and fully filled. But that will be a big test suite to add, we should add it in separate PR(s)

**Comment by sidorares** [comment]
Yes agree ( in general, having unit tests for all packets would be good)

**Pull request merged**
