### PR TITLE
Add Simplified Chinese support for README.md

### PR DESCRIPTION
**Pull request by WenisOK**

### CODE REVIEW

**Comment by sidorares** [comment]
Thanks for the contribution @WenisOK !

Small nit: can we add something like subheader "Translations in other languages" and have list of links under it ( currently with only zh-cn entry.

Without subheader/line break main header is a bit broken:

image

Also would be great if someone who can read Simplified Chinese could proof reed the documentation ( unfortunately I don't speak it ). Tagging @cweijan ( TODO: find more people I can ask for help here )

**Comment by cweijan** [comment]
Hi, I have reviewed the document in detail, it is a direct Chinese translation of the readme, and the document is indeed valid.
And I agree that the location of the document should have new lines.

**Comment by WenisOK** [comment]
OK, thank you for recognizing my translation. I will fix these problems at about 12:00 Beijing time.

**Comment by WenisOK** [comment]
Hello, I have solved the problem you said, please refer to

**Comment by sidorares** [comment]
Thanks for your work @WenisOK and thanks for review @cweijan , I'm happy to merge unless you intend to push more changes

**Pull request merged**
