### PR TITLE
feat(poolCluster): add promise version

### LINKED ISSUE #609: The createPoolCluster for the Promised version of node-mysql2 does not exist!
Here is my test code! 
```js
import mysql from 'mysql2/promise';
const dbCfg = {
    cluster: {
        removeNodeErrorCount: 2,
        restoreNodeTimeout: 50000,
        defaultSelector: 'RR'
    },
    pools: {
        'MASTER': {
            host: '192.168.1.10',
            port: 3306,
            user: 'webusr',
            database: 'test',
            password: '111111',
            charset:'utf8mb4',
            supportBigNumbers:true,
            connectionLimit:5
        }
    }
}

async function main(){
    /*
     * The mysql.createPoolCluster function doesn't exist!
     * If you replace the following statement:
     *    import mysql from 'mysql2/promise';
     * with the following statement:
     *    import mysql from 'mysql2';
     * and replace the following statement:
     *    const dbCluster = await mysql.createPoolCluster();
     * with this following statement:
     * const dbCluster = await mysql.createPoolClusterPromise;
     * you will still get error because the createPoolCluster is not implemented in mysql2/promise.js.
     */
    const dbCluster = await mysql.createPoolCluster();// This statement has an error!

    Object.keys(dbCfg.pools).forEach(function (nodeName) {
        dbCluster.add(nodeName, dbCfg.pools[nodeName]);
    })

    let db = null, rows = null, fields=null;

    try {
        db = await dbCluster.getConnection('*', 'ORDER');
        [rows, fields] = await db.execute('SELECT * FROM `pp` WHERE `id` > ?', [3]);
    } catch (e) {
        console.log('query error {{{{{ ');
        console.log(e);
        console.log('query error }}}}} ');
    }

    console.log('show results ======>');
    console.log(rows);
    console.log(fields);
}

main().catch(function (e) {
    console.log('main error {{{{{ ');
    console.log(e);
    console.log('main error }}}}} ');
});
```
Here is the info message:
```sh
wusheng@wusheng-pc MINGW64 /e/work/node-practice/mysql
$ node run.js test-cluster.js
main error {{{{{
TypeError: _promise2.default.createPoolCluster is not a function
    at main (E:/work/node-practice/mysql/test-cluster.js:35:35)
    at Object.<anonymous> (E:/work/node-practice/mysql/test-cluster.js:57:1)
    at Module._compile (module.js:569:30)
    at loader (E:\work\node-practice\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\work\node-practice\node_modul
es\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
main error }}}}}

```

### PR DESCRIPTION
**Pull request by yuxizhe**
fix #609 
add promise version of poolCluster

### CODE REVIEW

**Comment by vlasky** [comment]
@yuxizhe can you please add support for execute() as well.

**Comment by yuxizhe** [comment]
> @yuxizhe can you please add support for execute() as well.

no problem，I will make a PR soon.

**Comment by vlasky** [comment]
@yuxizhe thanks really look forward to it!

**Comment by vlasky** [comment]
@yuxizhe how soon will you be able to add support for execute()?

**Comment by yuxizhe** [comment]
> @yuxizhe how soon will you be able to add support for execute()?

sorry, I've been busy recently, I will try to make a PR tonight

**Comment by vlasky** [comment]
Thanks so much @yuxizhe look forward to giving it a try!

**Pull request merged**
