### PR TITLE
fix(type): add promise missing typings and simplify code

### PR DESCRIPTION
**Pull request by yuxizhe**
add promise wrapper missing typings and simplify code.

fix [ #1184](https://github.com/sidorares/node-mysql2/issues/1184)   #804

### CODE REVIEW

**Comment by sidorares** [comment]
lgtm @yuxizhe , thanks for working on this.

Would you be able to add a simple test harness for typings? ( something as simple as `tsc test.ts` ) 
if not happy to merge as is

**Comment by yuxizhe** [comment]
@sidorares  Sure, I will add typings test for this.

**Comment by jmordica** [comment]
> @sidorares Sure, I will add typings test for this.

I can add the test if you aren't able to @yuxizhe?

**Comment by yuxizhe** [comment]
> > @sidorares Sure, I will add typings test for this.
> 
> I can add the test if you aren't able to @yuxizhe?

@jmordica Welcome, Thank you very much!

**Comment by sidorares** [comment]
Thsnks @jmordica currently there is zero checks for the validity of the typings, even the most basic one would be a great addition

**Comment by jmordica** [comment]
@sidorares this can be closed in lieu of #1610

**Pull request closed without merging**
