### PR TITLE
fix: add condition which allows code in callback to be reachable

### LINKED ISSUE #2375: Specifying rejectUnauthorized=true and verifyIdentity=false, unreachable code
When I specify rejectUnauthorized=true and verifyIdentity=false, I still get an error: 

`Hostname/IP does not match certificate's altnames: ...`

So it seems like `verifyIdentity` does not have any effect. Looking at the code it seems like lib/connection.js line 372 is unreachable:

https://github.com/sidorares/node-mysql2/blob/1d983fa46031a77c689faea5f69e6e0baa1b3de7/lib/connection.js#L372C19-L372C19

```
      const ca = readFileSync(path.join(__dirname, `/ssl-ca/amazon-root-ca-1.pem`)).toString() // RDS Proxy
      
      pool = await createConnection({
        host,
        user,
        password,
        database,
        port,
        ssl: {
          ca,
          rejectUnauthorized: true,
          verifyIdentity: false
        }
      })
```

### PR DESCRIPTION
**Pull request by juanheyns**
This PR addresses the problem reported in #2375 

Fixes #2375 

Relates to breaking changes introduced with #2119

Possible workaround for #2177
Relates to #2172

### CODE REVIEW

**Comment by juanheyns** [comment]
Manually tested against AWS RDS Proxy:

Screenshot 2024-01-16 at 8 56 53 PM
Screenshot 2024-01-16 at 8 56 21 PM

**Comment by sidorares** [comment]
LGTM, thanks @juanheyns

**Comment by sidorares** [comment]
@juanheyns would this change make #2253 unnecessary?

**Comment by juanheyns** [comment]
> @juanheyns would this change make #2253 unnecessary?

Yes it would seem so.

**Comment by sidorares** [comment]
@juanheyns published as v3.7.1, thanks!

while the code around this change in your active memory - could you also please help reviewing #2295 ? That would be a minor version bump as it adds `checkServerIdentity` option. I don't like the fact that we would have 2 similarly named flags ( one is flag, one is function with custom check logic ), but might still worth adding

**Pull request merged**
