### PR TITLE
feat: make end resume command queue (partial #450)

### PR DESCRIPTION
**Pull request by gajus**
Enable `end` method to finish the command queue.

### CODE REVIEW

**Comment by dougwilson** [comment]
Would this have unintended consequences? What is `.end()` just destroyed the connection if it was paused? If you want to go with the auto resume, should it not auto resume on _any_ new packet added to the queue, not just end? i.e. if you did change user on a connection that was paused, you'd end up in the same situation as your original issue.

**Comment by gajus** [comment]
@dougwilson I have added more information about the issue https://github.com/sidorares/node-mysql2/issues/450#issuecomment-257899247.

The only reason I am proposing to "resume" command queue on "end" is because:

> [Closing the connection is done using end() which makes sure all remaining queries are executed before sending a quit packet to the mysql server.](https://github.com/mysqljs/mysql/tree/5cc6c6801ba91c5f15114ccf0fd55efd5317febb#introduction)

Unless I misunderstood the code, at the moment, if the command queue is paused and you call "end" it will terminate the command queue at once.

**Comment by sidorares** [comment]
IMO adding command (any, not just `end`) should not resume stream automatically.

What might help is after each callback the paused state is returned back to what it was before (even if exception was thrown from callback function)

**Comment by gajus** [comment]
> IMO adding command (any, not just end) should not resume stream automatically.

Whats the distinction then between `end` and `destroy`? My understanding is that one is supposed to complete the outstanding command queue and the other one must abort as soon as possible.

I might be wrong though. My familiarity with the code base and with the streams is limited.

**Comment by sidorares** [comment]
yes, `.end()` adds `[COM_QUIT](https://dev.mysql.com/doc/internals/en/com-quit.html)` command to the end of the queue, and connection is closed by server as a result when command is executed (commands in single connection are executed sequentially by server). `destroy()` closes client connection immediately and if there are connections in the queue left their completion callbacks called with error

**Comment by gajus** [comment]
Therefore, doesn't it make sense that `end` resumes the command queue?

Alternatively, `end` could throw an error if command queue is paused when `end` is called. I think I prefer this approach.

**Comment by sidorares** [comment]
if stream is paused, you never get to the point where `end()` command starts executing

> Alternatively, end could throw an error if command queue is paused when end is called.

I think it should not matter if stream is paused or not when you put commands to the queue. There is `end()`  method that adds command to the queue and there is `COM_QUIT` command itself

**Comment by gajus** [comment]
I am closing this PR since it looks like I am overlooking something. Please re-open it if you'd like to discuss this further.

**Pull request closed without merging**
