### PR TITLE
Update pool.js

### PR DESCRIPTION
**Pull request by hugnosis**
[performance]
double-ended-queue: 1240 ms
pattern/queue: 255 ms

### CODE REVIEW

**Comment by sidorares** [comment]
could you show benchmarks used?

Also interesting to compare performance for command queue - https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L42-L46

**Comment by sidorares** [comment]
Also just noticed that pool.js is using splice on queues ( originally Array was used as container ) - https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L42-L46

need to check if `Pool._removeConnection` is used at all

**Comment by sidorares** [comment]
results I have using [benchmark](https://github.com/petkaantonov/deque/blob/master/benchmark/thousand.js) from double-ended-queue:

```
double-ended-queue x 19,347,920 ops/sec ±8.16% (84 runs sampled)
pattern-queue x 2,646,092 ops/sec ±2.13% (85 runs sampled)
node-deque x 10,957,111 ops/sec ±15.80% (87 runs sampled)
built-in array x 2,410,360 ops/sec ±2.23% (92 runs sampled)
```

**Comment by hugnosis** [comment]
Sorry, there was a bug in my tests.
Thanks to your response.

**Comment by sidorares** [comment]
no problems, thanks for interest!

**Pull request closed without merging**
