### PR TITLE
fix: move `enableKeepAlive` and `keepAliveInitialDelay` options to `C…

### PR DESCRIPTION
**Pull request by wellwelwel**
Fixes:
- #2286

### CODE REVIEW

**Comment by luisasalas** [comment]
@wellwelwel How can I become a contributor to this project?

**Comment by sidorares** [comment]
@luisasalas if you are comfortable with the codebase you can start with PRs, either some changes important to you personally or something that is good for learning. We have https://github.com/sidorares/node-mysql2/labels/good%20first%20contribution and https://github.com/sidorares/node-mysql2/labels/good%20first%20issue labels but currently issues are not labeled really thoroughly 

Non code contributions - check currently open issues, answer questions, mark issues that are no longer relevant as ready to be closed, ask for more clarifications when its clearly incomplete etc etc

**Comment by wellwelwel** [comment]
@luisasalas, this is still developing, but we are also planning to migrate the documentation to a website (#2279) and the central idea is to document MySQL2 in its entirety.

Any help on this would be great 📖✨

**Comment by tfrancois** [comment]
Absolutely love and extremely grateful that this IMPORTANT library is continuously being maintained, updated and supported! Happy holidays!

**Comment by luisasalas** [comment]
@sidorares Sounds good, I'll comb through issues and try to tackle a good first issue.

@wellwelwel Interesting thanks for pointing that out, I'll take a look!

**Pull request merged**
