### PR TITLE
add eslint

### PR DESCRIPTION
**Pull request by sidorares**

### CODE REVIEW

**Comment by gajus** [comment]
@sidorares @e44db03b5928383d8c61671103d53f880c2680b5 fixes most of the open linting rules.

I would like to add a few more rules to the `.eslintrc`:

* `"curly": 2`
* `"indent": [2, 4]` (or `"indent": [2, 2]` if thats your preference)

Please comment whether you are happy with all/either of these changes. I will update the `.eslintrc` and code style.

**Comment by sidorares** [comment]
yes, I'm ok with that ( what's the difference between `"indent": [2, 4]`  and `"indent": [2, 2]` ? I prefer to use 2 space indentation )

**Comment by gajus** [comment]
@sidorares I have added a few more rules. Please review. If you'd like to revert either of the rules, lets discuss.

**Comment by gajus** [comment]
@sidorares Is there anything else I can do to expedite this merge? Otherwise, solving conflicts will be an endless battle.

**Comment by sidorares** [comment]
@gajus trying to fix failing tests, hope to finish today

**Comment by gajus** [comment]
@sidorares Do you want me to help with either of the test cases? If yes, which one?

**Pull request merged**
