### PR TITLE
provide changeUser implementation in promise.js

### PR DESCRIPTION
**Pull request by rhyek**

### CODE REVIEW

**Comment by rhyek** [comment]
Fixes #613.

**Comment by sidorares** [comment]
can I ask you to add test?

non-promise integration for test is here - test/integration/connection/test-change-user.js
currently all promise wrapper tests live here: /test/integration/promise-wrappers/test-promise-wrappers.js but I think it's time to split them into multiple files

**Comment by rhyek** [comment]
Sorry for not answering earlier. Sure, I'll work on that tomorrow. Thanks.

**Comment by rhyek** [comment]
@sidorares could you shed some light on these failures? Logs mention the 'bad sql' query in the already present tests.

**Comment by sidorares** [comment]
'bad sql' is where I test async stack traces, this is intended error (need to remove logging of it)

are you able to run tests locally? This is relatively easy with docker

**Comment by rhyek** [comment]
I'm on Windows 10 Home. Forced to use docker-machine and am getting all sorts of errors which I'm sure are related to my environment. For example:
<pre>
[0:00:51 65 20/86 98.8% node test\integration\connection\encoding\test-track-encodings.js]

  assert.js:586
  assert.ifError = function ifError(err) { if (err) throw err; };
                                                    ^

  Error: Access denied for user 'root'@'localhost' (using password: NO)
      at Packet.asError (C:\Users\Carlos\dev\contributions\thirdparty\node-mysql2\lib\packets\packet.js:701:13)
      at ClientHandshake.Command.execute (C:\Users\Carlos\dev\contributions\thirdparty\node-mysql2\lib\commands\command.  :28:22)
      at Connection.handlePacket (C:\Users\Carlos\dev\contributions\thirdparty\node-mysql2\lib\connection.js:515:28)
      at PacketParser.onPacket (C:\Users\Carlos\dev\contributions\thirdparty\node-mysql2\lib\connection.js:94:16)
      at PacketParser.executeStart (C:\Users\Carlos\dev\contributions\thirdparty\node-mysql2\lib\packet_parser.js:77:14)
      at Socket.<anonymous> (C:\Users\Carlos\dev\contributions\thirdparty\node-mysql2\lib\connection.js:102:29)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:252:12)
      at readableAddChunk (_stream_readable.js:239:11)
</pre>

**Comment by sidorares** [comment]
do you start db in another container? try to check that you linked them correctly via `--link` + `--name` or using docker networks

**Comment by sidorares** [comment]
```
docker network create mysqltest --subnet=192.168.0.0/16
docker run -d - --net=cmysqltest  --ip=192.168.0.3 --name=db -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_DATABASE=test -p 3306:3306 mysql:5.7
docker run -it -v /node-mysql2 your-test-folder node:latest /bin/bash
```
then you can start tests passing host name as `MYSQL_HOST=192.168.0.3 ( haven't tested commands above, please check them first )

**Comment by rhyek** [comment]
`docker run -d - --net=mysqltest  --ip=192.168.0.3 --name=db -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_DATABASE=test -p 3306:3306 mysql:5.7`

produces:
<pre>
C:\Program Files\Docker Toolbox\docker.exe: invalid reference format.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
</pre>

**Comment by sidorares** [comment]
sorry, there is typo with extra ' - '

I'm on windows machine right now, ` docker run -d --net=mysqltest  --ip=192.168.0.3 --name=db -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_DATABASE=test -p 3306:3306 mysql:5.7` worked for me

**Comment by rhyek** [comment]
Inside the second container, running `npm run test:raw` I get:
<pre>
[0:00:05 4 8/86 14.0% node test/integration/connection/test-binary-charset-string.js]

  /node-mysql2/test/integration/connection/test-binary-charset-string.js:25
      throw err;
      ^

  Error: connect ECONNREFUSED 127.0.0.1:3306
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
</pre>

I appreciate your help here, but I was hoping your CI pipeline would be able to just run the test I coded for you. If you are able to get the tests working that is great. You are free to merge or close this PR.

Maybe a small contribution guideline explaining how to set all this up would not be such a bad idea.

**Comment by sidorares** [comment]
> Maybe a small contribution guideline explaining how to set all this up would not be such a bad idea.

yes, definitely a good idea

>  Error: connect ECONNREFUSED 127.0.0.1:3306

I wonder why it's 127.0.0.1 and not server ip which would be 192.168.0.3

anyway if you're stuck and have to move to other things - no problems, I'll have a look at your tests later today

**Comment by sidorares** [comment]
@rhyek  the issue was that promise resolves to `[rows, fields]` array and you assumed it's `rows`. Thanks for PR, your code merged via #615

**Comment by rhyek** [comment]
Gotcha. Sorry about that. Thanks for helping out.

**Pull request merged**
