### PR TITLE
added connect timeout event and tests

### PR DESCRIPTION
**Pull request by sushantdhiman**
Closes https://github.com/sidorares/node-mysql2/issues/376

### CODE REVIEW

**Comment by sushantdhiman** [comment]
@sidorares One unrelated thing, I was working on implementing LRU cache and I find out something odd [here](https://github.com/sidorares/node-mysql2/blob/ab51adfb47879c9f5c946fd9ac53eb6aab7343b4/lib/commands/query.js#L171), `this.rowParser` is always `undefined`, I think we need to use `this._rowParser`. So our cache is currently not being used at all.

But real problem starts after using `this._rowParser`, we get errors like this

```js
[0:01:03 0 69/75 92.0% node test/integration/connection/test-typecast-global-option.js] 
  
  evalmachine.<anonymous>:15
    this["foo"] = options.typeCast(wrap(fields[0], "VAR_STRING", packet, "utf8"), function() { return packet.readLengthCodedString("utf8");})
                          ^
  
  TypeError: options.typeCast is not a function
      at new TextRow (evalmachine.<anonymous>:15:25)
      at Query.row (/var/www/github/node-mysql2/lib/commands/query.js:198:13)
      at Query.Command.execute (/var/www/github/node-mysql2/lib/commands/command.js:38:20)
      at Connection.handlePacket (/var/www/github/node-mysql2/lib/connection.js:339:28)
      at PacketParser.onPacket (/var/www/github/node-mysql2/lib/connection.js:83:66)
      at PacketParser.executeStart (/var/www/github/node-mysql2/lib/packet_parser.js:45:12)
      at Socket.<anonymous> (/var/www/github/node-mysql2/lib/connection.js:86:29)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at readableAddChunk (_stream_readable.js:177:18)
  
[0:01:03 1 69/75 93.3% node test/integration/connection/test-typecast.js]               
  
  evalmachine.<anonymous>:15
    this["foo"] = options.typeCast(wrap(fields[0], "VAR_STRING", packet, "utf8"), function() { return packet.readLengthCodedString("utf8");})
                          ^
  
  TypeError: options.typeCast is not a function
      at new TextRow (evalmachine.<anonymous>:15:25)
      at Query.row (/var/www/github/node-mysql2/lib/commands/query.js:198:13)
      at Query.Command.execute (/var/www/github/node-mysql2/lib/commands/command.js:38:20)
      at Connection.handlePacket (/var/www/github/node-mysql2/lib/connection.js:339:28)
      at PacketParser.onPacket (/var/www/github/node-mysql2/lib/connection.js:83:66)
      at PacketParser.executeStart (/var/www/github/node-mysql2/lib/packet_parser.js:45:12)
      at Socket.<anonymous> (/var/www/github/node-mysql2/lib/connection.js:86:29)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at readableAddChunk (_stream_readable.js:177:18)
  
[0:01:03 2 69/75 94.7% node test/unit/protocol/test-SqlString.js]         
  
  0 fail | 37 pass | 6 ms 
  
[0:01:03 2 70/75 96.0% node test/integration/connection/encoding/test-charset-results.js]
  
  assert.js:89
    throw new assert.AssertionError({
    ^
  AssertionError: 'РТЙЧЕФ, НЙТ' == 'привет, мир'
      at Query.onResult (/var/www/github/node-mysql2/test/integration/connection/encoding/test-charset-results.js:18:14)
      at /var/www/github/node-mysql2/lib/commands/query.js:56:14
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

I am investigating further to track this issue

**Comment by sidorares** [comment]
@sushantdhiman what do you think about starting using release branches? 1.x etc?
I think I'll release 1.0 today and this change and some others would go to 1.1

**Comment by sushantdhiman** [comment]
No problem, we can add this to 1.1

**Comment by sidorares** [comment]
1.1 - this was re main PR. very keen to make caching bug fix into 1.0, will look into it now

**Comment by sidorares** [comment]
@sushantdhiman see #397

**Comment by sidorares** [comment]
@sushantdhiman could you rebase this?

What's default value for timeout?

You are using Net.Socket `setTimeout` - this probably won't work for custom streams. Maybe we should just use timers? set it when client created and clear on first packet?

**Comment by sushantdhiman** [comment]
> What's default value for timeout?

10 sec

> You are using Net.Socket setTimeout - this probably won't work for custom streams. Maybe we should just use timers? set it when client created and clear on first packet?

Ok, I'll use timers

**Comment by sushantdhiman** [comment]
@sidorares updated with timers

**Comment by sidorares** [comment]
related issues: #185 https://github.com/sidorares/node-mysql2/issues/373#issuecomment-240466002

**Comment by sidorares** [comment]
lgtm - I think it's good to merge if you are done here @sushantdhiman

**Pull request merged**
