### PR TITLE
fix issue #1040

### PR DESCRIPTION
**Pull request by lirancr**
https://github.com/sidorares/node-mysql2/issues/1040

### CODE REVIEW

**Comment by lirancr** [comment]
@sidorares pinging you about the travic ci failing for some unknown reason

**Comment by sidorares** [comment]
this is what was causing failure - https://github.com/sidorares/node-mysql2/commit/26d1de97a068670fd153cb8c3de537bd4a1c0e35#diff-d96ea1829b57eb6cd5fb13eb40dbd17dR60-R68 (latest mysql 8 tag moved to be `8.0.18` and tests started to fail without any change on library  side)

I'll re-run this pr

**Comment by lirancr** [comment]
@sidorares hate to nag but.... :D

**Comment by lirancr** [comment]
@sidorares been a while. any chance you could take another look ?

**Comment by sidorares** [comment]
I'll try tomorrow :) sorry for delays @lirancr

**Comment by lirancr** [comment]
@sidorares

**Comment by sidorares** [comment]
🤦 really sorry, and thanks for your patience and keeping pinging me. I'll try to merge as soon as I can

**Comment by lirancr** [comment]
closing PR since its been getting stale. would reopen once CI is sane

**Pull request closed without merging**
