### PR TITLE
Add default connection attributes

### PR DESCRIPTION
**Pull request by Daemonxiao**
MySQL connectors have some [Available Connection Attributes](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html).

I add the following built-in connection attributes to Node-MySQL-2.
```
{
  '_client_name': 'Node-MySQL-2',
  '_client_version': version
}
```

These attributes will help users distinguish which driver the connection comes from.

### CODE REVIEW

**Comment by sidorares** [comment]
LGTM, thanks for adding this @Daemonxiao 

could you link mysql docs in a comment and add few words explaining what/why these attributes are ( and that names are not something we made up and are common agreed )

Also can you rewrite a commit message to follow https://www.conventionalcommits.org/en/v1.0.0/

( also - might need to rebase once again a bit later, currently PlanetScale check is failing for some reason. I'll try to fix or disable that today )

**Comment by Daemonxiao** [comment]
@sidorares Thanks for your review. I have rewritten the commit message. Does it meet the requirements? Please feel free to tell me if you have any advice.

**Comment by sidorares** [comment]
> Does it meet the requirements? Please feel free to tell me if you have any advice.

Yep, perfect. release-please is using commit messages to automatically populate feature / release / core section of the release post, and also only prepares a release if there a new "releasable items" since the last one.

**Comment by sidorares** [comment]
Maybe it's better to move the change to connection_config, where other default connection parameters are
Also maybe worth leaving a way to override attributes if they are passed, for example here

https://github.com/sidorares/node-mysql2/blob/2c1b4bc3d84336927329312393d0afbc9761f76f/lib/connection_config.js#L172

use line like

```js
const defaultConnectAttributes =  {
  _client_name: 'Node-MySQL-2',
  _client_version: version
};
this.connectAttributes = { ...defaultConnectAttributes, ...(options.connectAttributes || {}));
```

**Comment by Daemonxiao** [comment]
> Maybe it's better to move the change to connection_config, where other default connection parameters are
Also maybe worth leaving a way to override attributes if they are passed, for example here
@sidorares Thank you very much. This really excellent advice. I have applied it in[ nearly commit](https://github.com/sidorares/node-mysql2/pull/1825/commits/f46c7f43c0cf4c4fafecc67f9cfdb7c000e56e76).

**Comment by sidorares** [comment]
@Daemonxiao some unit tests are failing, could you try running them locally?

**Comment by Daemonxiao** [comment]
> some unit tests are failing, could you try running them locally?

@sidorares Done.

**Comment by Daemonxiao** [comment]
@sidorares Is this pr ready to be merged? Or is there anything else I can do?

**Pull request merged**
